### PR TITLE
[Fix] `no-unused-prop-types`: false positive with callback

### LINKED ISSUE #2350: react/no-unused-prop-types false positive in useEffect with destructuring
It seems that destructuring props inside of useEffect causes the `react/no-unused-prop-types` error to be triggered despite the prop being used. In the example below, calling the prop as `prop.loggedIn` instead of first destructuring it will fix the issue and make the error go away.

```
useEffect(() => {
	const { loggedIn, isAdmin } = props;
	.....
}, []);
```

### PR DESCRIPTION
**Pull request by golopot**
Fixes #2350

This pr fixes `getParentStatelessComponent` when the current traversed node is like a callback (is a function and is an argument). The function `getParentStatelessComponent` is revised to use a more whitelist-ish approach.

Fixes false positive like:
```js
function Foo(props) {
  useEffect(() => {
    const { a } = props;
    document.title = a;
  });
  
  return <p/>;
}
  Foo.propTypes = {
  a: PropTypes.string,
}
```

### CODE REVIEW

File: tests/lib/rules/no-this-in-sfc.js [hunk 1]
```diff
@@ -217,13 +217,6 @@ ruleTester.run('no-this-in-sfc', rule, {
       return <div onClick={onClick}>{this.props.foo}</div>;
     }`,
     errors: [{message: ERROR_MESSAGE}, {message: ERROR_MESSAGE}]
-  }, {
-    code: `
-    () => {
-      this.something();
-      return null;
-    }`,
-    errors: [{message: ERROR_MESSAGE}]
```
Comment (golopot) [inline tests/lib/rules/no-this-in-sfc.js]: This test case is moot. It is an unused expression.

File: lib/util/Components.js [hunk 2]
```diff
@@ -512,43 +512,35 @@ function componentRule(rule, context) {
...
-      while (scope) {
-        if (astUtil.isFunction(scope.block) || astUtil.isClass(scope.block)) {
-          return scope;
+        if (node.type === 'FunctionExpression' || node.type === 'ArrowFunctionExpression') {
+          switch (node.parent.type) {
+            case 'VariableDeclarator':
+            case 'AssignmentExpression':
+            case 'Property':
+            case 'ReturnStatement':
+            case 'ExportDefaultDeclaration': {
```
Comment (golopot) [inline lib/util/Components.js]: These cases are
```js
const Foo = () => <p />;

module.exports = function Foo() {};

module.exports = {
  Foo() {},
};

function hof() {
  return function Foo() {};
}

export default function Foo() {}
```

File: tests/lib/rules/no-this-in-sfc.js (hunk 1 above)
Comment (ljharb) [reply tests/lib/rules/no-this-in-sfc.js]: i'm not sure why; it's still a usage of `this` that someone might expect to have side effects.

File: lib/util/Components.js (hunk 2 above)
Comment (ljharb) [reply lib/util/Components.js]: Can we add explicit test cases for each of them?

File: tests/lib/rules/no-this-in-sfc.js (hunk 1 above)
Comment (golopot) [reply tests/lib/rules/no-this-in-sfc.js]: I mean the arrow function is not reference-able and the program is equivalent to no-op, therefore it should never happen in real world code.

Comment (ljharb) [reply tests/lib/rules/no-this-in-sfc.js]: ah fair, since the arrow function won't be recognized as a component.

File: lib/util/Components.js (hunk 2 above)
Comment (golopot) [reply lib/util/Components.js]: Currently the tests cases for them are scattered in several rules, do you want a set of test cases centralized in, say, `tests/rules/prop-types.js`?

Comment (ljharb) [reply lib/util/Components.js]: it'd probably be ideal for every rule that uses component detection to have all of these cases, tbh

**Comment by golopot** [comment]
The tests are broken by the merge of #2184, which added a test case: https://github.com/yannickcr/eslint-plugin-react/blob/7bc55ccb6ed2c32d381f09d2f43a77ca60afaae3/tests/lib/rules/no-multi-comp.js#L345-L349

Do we want to support components defined in comma operator? (IMO, no.)

**Comment by ljharb** [comment]
Yes, we should support components in any expression position.

File: lib/util/Components.js [hunk 3]
```diff
@@ -581,45 +581,62 @@ function componentRule(rule, context) {
...
-        // Attribute Expressions inside JSX Elements (<button onClick={() => props.handleClick()}></button>)
-        const isJSXExpressionContainer = node.parent && node.parent.type === 'JSXExpressionContainer';
-        const pragmaComponentWrapper = this.getPragmaComponentWrapper(node);
-        if (isFunction && pragmaComponentWrapper) {
-          return pragmaComponentWrapper;
+      /**
+       * @param {ASTNode} node
+       * @returns {boolean}
+       */
+      function isInAllowedPositiionForComponent(node) {
```
Comment (ljharb) [inline lib/util/Components.js]: Also, this function should be moved up to module level, so it's not recreated for each invocation of this method.
```suggestion
      function isInAllowedPositionForComponent(node) {
```

File: lib/util/Components.js [hunk 4]
```diff
@@ -581,45 +581,62 @@ function componentRule(rule, context) {
...
+        switch (node.parent.type) {
+          case 'VariableDeclarator':
+          case 'AssignmentExpression':
+          case 'Property':
+          case 'ReturnStatement':
+          case 'ExportDefaultDeclaration': {
+            return true;
+          }
+          case 'SequenceExpression': {
+            return isInAllowedPositiionForComponent(node.parent) &&
```
Comment (ljharb) [inline lib/util/Components.js]:
```suggestion
            return isInAllowedPositionForComponent(node.parent) &&
```

File: lib/util/Components.js [hunk 5]
```diff
@@ -581,45 +581,62 @@ function componentRule(rule, context) {
...
+          if (utils.isReturningJSXOrNull(node)) {
+            return node;
+          }
         }
-        // Return the node if it is a function that is not a class method and is not inside a JSX Element
-        if (isFunction && !isMethod && !isJSXExpressionContainer && utils.isReturningJSXOrNull(node)) {
-          return node;
+
+        if (node.type === 'FunctionExpression' || node.type === 'ArrowFunctionExpression') {
+          if (isInAllowedPositiionForComponent(node) && utils.isReturningJSXOrNull(node)) {
```
Comment (ljharb) [inline lib/util/Components.js]:
```suggestion
          if (isInAllowedPositionForComponent(node) && utils.isReturningJSXOrNull(node)) {
```

File: lib/util/Components.js [hunk 6]
```diff
@@ -581,45 +581,62 @@ function componentRule(rule, context) {
...
-          return null;
+      }
+
+      /**
+       * Get node if node is a stateless component, or node.parent in cases like
+       * `React.memo` or `React.forwardRef`. Otherwise returns `undefined`.
+       * @param {ASTNode} node
+       * @returns {ASTNode | undefined}
+       */
+      function getStatelessComponent(node) {
```
Comment (ljharb) [inline lib/util/Components.js]: this function should also be hoisted up to module level

Comment (golopot) [reply lib/util/Components.js]: I 100% prefer hoisted functions, but in this case, hoisting up this function will move it very far away from its usage (because the functions are in a giant `utils` object literal), which I do not feel good about.

Comment (ljharb) [reply lib/util/Components.js]: Perhaps i shouldn't have used the word "hoisted" :-) i don't like hoisting, but i think functions should be defined as far away as possible to maximize reuse.

Comment (golopot) [reply lib/util/Components.js]: Hoisting is a word with overloaded meanings. I mean `hoisted` as `not nested function`. 

I feel functions dealing with the same topic should be co-located close together, so that reader do not need to jump around to understand a functionality.

Comment (ljharb) [reply lib/util/Components.js]: I think that's fine when the two positions are equivalent; in this case it will impact performance since it will be creating a new function many times, instead of reusing the same one from before.
