### PR TITLE
[Fix] `jsx-no-target-blank`: allow rel to be an expression

### LINKED ISSUE #2508: jsx-no-target-blank usage with jsx-curly-brace-presence
eslint: 6.7.2
eslint-plugin-react: 7.17.0
eslint config: https://gist.github.com/robertgorbul/414e99899a12b56fef8d6ec9db4bf72e
```
29:11 Using target="_blank" without rel="noopener noreferrer" is a security risk: see https://mathiasbynens.github.io/rel-noopener
  27 |         href={'https://www.gatsbyjs.org'}
  28 |         aria-label={'Gatsby.js - Blazing fast modern site generator for React'}
> 29 |         target={'_blank'}
     |         ^
  30 |         rel={'noopener noreferrer'}
  31 |         >
  32 |         Gatsby
```
```
30:15 Need to wrap this literal in a JSX expression.
    28 |    aria-label={'Gatsby.js - Blazing fast modern site generator for React'}
    29 |    target={'_blank'}
  > 30 |    rel='noopener noreferrer'
       |    ^
    31 |    >
    32 |      Gatsby
    33 |    </a>
```

### PR DESCRIPTION
**Pull request by odinho**
Previously this would be an error, since the rel wasn't read:

    <a target={"_blank"} href={"//"} rel={"noopener noreferrer"}>

Now this works, so you can enable this rule together with
`jsx-curly-brace-presence`.

Fixes #2508.

### CODE REVIEW

**Comment by ljharb** [comment]
Since you made this PR from a fork that isn't your own, I'm unable to force push to it (due to a github bug that they're unlikely to fix because so few people do this); would you mind adding me to https://github.com/whereby/eslint-plugin-react so i can?

File: tests/lib/rules/jsx-no-target-blank.js [hunk 1]
```diff
@@ -35,18 +35,23 @@ ruleTester.run('jsx-no-target-blank', rule, {
     {code: '<a href="foobar"></a>'},
     {code: '<a randomTag></a>'},
     {code: '<a target />'},
+    {code: '<a target={null}></a>'},
```
Comment (ljharb) [inline tests/lib/rules/jsx-no-target-blank.js]: this isn't a valid `target` attribute value; it might even result in a runtime warning from react.

**Comment by odinho** [comment]
Added you as "write" collaborator.

Updated tests, removed `target={null}` and added one `'` and one <code>`</code> test.

> Since you made this PR from a fork that isn't your own, I'm unable to force push to it (due to a github bug that they're unlikely to fix because so few people do this); would you mind adding me to https://github.com/whereby/eslint-plugin-react so i can?

Ouch. That feels weird. I'm an organization member on that one though. -- But I'll use my private user place next time :)
