### PR TITLE
Fix false positives for display-name

### LINKED ISSUE #2269: False positive display-name when using forwardRef
**Tell us about your environment**

* **ESLint Version:** 5.16.0
* **Node Version:** 10.12.0
* **npm Version:** 6.9.0

**What parser (default, Babel-ESLint, etc.) are you using?** babel-eslint 10.0.1

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
    "env": {
        "browser": true,
        "es6": true
    },
    "extends": [
        "eslint:recommended",
        "plugin:react/recommended"
    ],
    "parserOptions": {
        "ecmaVersion": 9,
        "sourceType": "module",
        "ecmaFeatures": {
            "jsx": true
        }
    },
    "rules": {
        "indent": [
            "error",
            2,
            { "SwitchCase": 1 }
        ],
        "linebreak-style": [
            "error",
            "unix"
        ],
        "no-console": "warn",
        "quotes": [
            "error",
            "single"
        ],
        "semi": [
            "error",
            "always"
        ]
    }
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
import PropTypes from 'prop-types';
import React from 'react';

const Paragraph = React.forwardRef(function Paragraph({ style }, ref) {
  // const finalStyle = Object.assign({}, style);
  return <div ref={ref} style={style} />;
});

Paragraph.propTypes = {
  style: PropTypes.object
};

export default Paragraph;
export const proptype = Paragraph.PropTypes;
```

```bash
npx eslint <file>
```

**What did you expect to happen?**
Nothing as the file is valid

**What actually happened? Please include the actual, raw output from ESLint.**

```
  4:19  error  Component definition is missing display name  react/display-name

✖ 1 problem (1 error, 0 warnings)
```

**Fun fact!** If you uncomment the line with Object.assign, the false positive disappears...

### LINKED ISSUE #2324: display-name triggered on default export using React.memo
This issue was originally reported by @jwalton in #2133. Confirmed that issue exists in 7.13.0 and 7.14.1 (we are not using typescript in our project).

> simple solution there, use a default export :-D

In latest build, this appears to be broken for a default export (although... I'm in a typescript project, so this *might* be a problem specific to linting .tsx files):

```ts
export default React.memo(function LabelControl(props: ControlProps) {
    const control = props.control as OnDemandLabelControl;

    return (
        <ControlWrapper>
            <Translate tagName="h2" message={control.title} />
        </ControlWrapper>
    );
});
```

triggers react/display-name, but:

```ts
function LabelControl(props: ControlProps) {
    const control = props.control as OnDemandLabelControl;

    return (
        <ControlWrapper>
            <Translate tagName="h2" message={control.title} />
        </ControlWrapper>
    );
}

export default React.memo(LabelControl);
```

does not.

_Originally posted by @jwalton in https://github.com/yannickcr/eslint-plugin-react/issues/2133#issuecomment-502449263_

### PR DESCRIPTION
**Pull request by BPScott**
Wrapping a named function declaration with a React.memo or
React.forwardRef will no longer throw false positive errors.

Check how React devtools exposes the displayNames of components wrapped in memo and forwardRef in https://codesandbox.io/s/awesome-paper-hh0wh?module=App.js

The following no longer raise a linting warning (as react can determine displayNames for them):

```jsx
import React from 'react'

export const ComponentWithMemo = React.memo(function Component({ world }) {
 return <div>Hello {world}</div>
})

export const ComponentWithForwardRef = React.forwardRef(function Component({ world }) {
  return <div>Hello {world}</div>
})
```

Using either an unnamed Function declaration (`function() {/*...*/}`) or arrow functions continue to raise a warning, as a displayName can not be inferred.

Nesting memo and forwardref (`const Component = React.memo(React.forwardRef(function Component() { /*...*/}))` is not currently handled by react so continue to raise an error in that case (see facebook/react#16722)

Fixes #2324, Fixes #2269

### CODE REVIEW

File: lib/rules/display-name.js [hunk 1]
```diff
@@ -90,13 +90,13 @@ module.exports = {
       const namedClass = (
         (node.type === 'ClassDeclaration' || node.type === 'ClassExpression') &&
         node.id &&
-        node.id.name
+        !!node.id.name
```
Comment (BPScott) [inline lib/rules/display-name.js]: This and the below addition of `!!` aren't strictly needed but I spotted every other variable in this block returns a boolean so I figured these should too

File: tests/lib/rules/display-name.js [hunk 2]
```diff
@@ -672,6 +688,94 @@ ruleTester.run('display-name', rule, {
...
+    // right if you squint at it
+    // In this test the plugin identifies two components instead of one.
+    // React is unable to work out the displayName for this code so we're
+    // reporting the right thing, just doing it twice.
+    // I think ideally this should only report one error.
+    code: `
+      import React from 'react'
+
+      export const ComponentWithMemoAndForwardRef = React.memo(
+        React.forwardRef(({ world }) => {
```
Comment (ljharb) [inline tests/lib/rules/display-name.js]: the thing inside `forwardRef` is not a component, and should not be identified as such. `forwardRef` callbacks take props and `ref`, which isn't what components take.

File: tests/lib/rules/display-name.js [hunk 3]
```diff
@@ -672,6 +688,94 @@ ruleTester.run('display-name', rule, {
...
+    parser: parsers.BABEL_ESLINT,
+    errors: [{
+      message: 'Component definition is missing display name', line: 4
+    }, {
+      message: 'Component definition is missing display name', line: 5
+    }]
+  }, {
+    // React does not currently set a displayName on the memo function when you
+    // pass it a value from forwardRef.
+    // Hopefully eventually that will be fixed, but until then flagging this
```
Comment (ljharb) [inline tests/lib/rules/display-name.js]: this shouldn't be fixed because it's not broken; forwardRef is a component but does not accept one; it accepts a callback that takes `props` and `ref`.

Comment (BPScott) [reply tests/lib/rules/display-name.js]: I think I'm referring to a slightly different issue. I'm referring how React.memo handles accepting a Component vs the result of calling forwardRef.

When inspecting the MemoFunction and  MemoThenForwardRefFunction 
 items on https://codesandbox.io/s/awesome-paper-hh0wh?module=App.js I end up with the following in my react devtools:

Screen Shot 2019-09-02 at 11 28 43 PM

Note that calling React.memo with a function component defined inline

```jsx
const MemoFunction = React.memo(function MemoFunction() {
  return <div>MemoFunction</div>;
});
```

Results in in the name `MemoFunction [memo]` in the component tree.

However calling React.memo with an invocation of React.forwardRef (which returns a Component)

```jsx
const MemoThenForwardRefFunction = React.memo(
  React.forwardRef(function MemoThenForwardRefFunction() {
    return <div>MemoThenForwardRefFunction</div>;
  })
);
```

Results in the name `Anonymous` in the component tree  - Given that the result of an unwrapped call to React.forwardRef has a meaningful name, I would have expected that to have been picked up by React.memo

File: tests/lib/rules/display-name.js (hunk 2 above)
Comment (BPScott) [reply tests/lib/rules/display-name.js]: Gotcha, thanks for the clarification :)

In that case I think there is something off with the Component detection, as this testcase identifies two components (as found by doing a `console.log(components.list())` in the `Program:exit` function in the display-name rule). It sounds like it should only identify one - possibly the outer call to `React.memo`. This also occurs on master too.

I don't understand how the internals of component detection work to be confident in modifying it so only a single Component is discovered. It looks like 98d4bf31 did some work towards this.

File: tests/lib/rules/display-name.js (hunk 3 above)
Comment (BPScott) [reply tests/lib/rules/display-name.js]: I've raised this upstream as https://github.com/facebook/react/issues/16722

**Comment by BPScott** [comment]
Heya @ljharb, I've gave this a kick again and I think it is ready for review. I've updated the naming in the tests.

The functions that you pass into `forwardRef` are trixy - they're not quite components as you say, but you can set a `displayName` on them and that gets honored like regular components. Because they act like components in that sense I think it makes sense to use the existing componentt detection logic for them.

I'm torn on what to do when we have a nested `React.memo(React.forwardRef(/*...*/))`. It's marked as an error for now, but we can go back and revisit later.

File: tests/lib/rules/display-name.js [hunk 4]
```diff
@@ -672,6 +688,101 @@ ruleTester.run('display-name', rule, {
...
+    }]
+  }, {
+    code: `
+      import React from 'react'
+
+      const ForwardRefComponentLike = React.forwardRef(function({ world }, ref) {
+        return <div ref={ref}>Hello {world}</div>
+      })
+    `,
+    parser: parsers.BABEL_ESLINT,
```
Comment (ljharb) [inline tests/lib/rules/display-name.js]: does this need babel-eslint?

File: tests/lib/rules/display-name.js [hunk 5]
```diff
@@ -672,6 +688,101 @@ ruleTester.run('display-name', rule, {
...
+    }]
+  }, {
+    code: `
+      import React from 'react'
+
+      const ForwardRefComponentLike = React.forwardRef(({ world }, ref) => {
+        return <div ref={ref}>Hello {world}</div>
+      })
+    `,
+    parser: parsers.BABEL_ESLINT,
```
Comment (ljharb) [inline tests/lib/rules/display-name.js]: does this need babel-eslint?

File: tests/lib/rules/display-name.js [hunk 6]
```diff
@@ -672,6 +688,101 @@ ruleTester.run('display-name', rule, {
...
+    }]
+  }, {
+    code: `
+      import React from 'react'
+
+      const ComponentWithMemo = React.memo(function() {
+        return <div>Hello {world}</div>
+      })
+    `,
+    parser: parsers.BABEL_ESLINT,
```
Comment (ljharb) [inline tests/lib/rules/display-name.js]: does this need babel-eslint?

File: tests/lib/rules/display-name.js [hunk 7]
```diff
@@ -672,6 +688,101 @@ ruleTester.run('display-name', rule, {
...
     }]
+  }, {
+    code: `
+      import React from 'react'
+
+      const ComponentWithMemo = React.memo(({ world }) => {
+        return <div>Hello {world}</div>
+      })
+    `,
+    parser: parsers.BABEL_ESLINT,
```
Comment (ljharb) [inline tests/lib/rules/display-name.js]: does this need babel-eslint?

File: tests/lib/rules/display-name.js [hunk 8]
```diff
@@ -672,6 +688,101 @@ ruleTester.run('display-name', rule, {
...
+    code: `
+      import React from 'react'
+
+      const MemoizedForwardRefComponentLike = React.memo(
+        React.forwardRef(({ world }, ref) => {
+          return <div ref={ref}>Hello {world}</div>
+        })
+      )
+    `,
+    parser: parsers.BABEL_ESLINT,
```
Comment (ljharb) [inline tests/lib/rules/display-name.js]: does this need babel-eslint?

File: tests/lib/rules/display-name.js [hunk 9]
```diff
@@ -672,6 +688,101 @@ ruleTester.run('display-name', rule, {
...
+    code: `
+      import React from 'react'
+
+      const MemoizedForwardRefComponentLike = React.memo(
+        React.forwardRef(function({ world }, ref) {
+          return <div ref={ref}>Hello {world}</div>
+       })
+      )
+    `,
+    parser: parsers.BABEL_ESLINT,
```
Comment (ljharb) [inline tests/lib/rules/display-name.js]: does this need babel-eslint?

File: tests/lib/rules/display-name.js [hunk 10]
```diff
@@ -672,6 +688,101 @@ ruleTester.run('display-name', rule, {
...
+    code: `
+      import React from 'react'
+
+      const MemoizedForwardRefComponentLike = React.memo(
+        React.forwardRef(function ComponentLike({ world }, ref) {
+          return <div ref={ref}>Hello {world}</div>
+        })
+      )
+    `,
+    parser: parsers.BABEL_ESLINT,
```
Comment (ljharb) [inline tests/lib/rules/display-name.js]: does this need babel-eslint?

File: tests/lib/rules/display-name.js (hunk 4 above)
Comment (BPScott) [reply tests/lib/rules/display-name.js]: Nope, I've removed them all. (thanks for spotting the cargo culting as I copied from other tests)

**Comment by BPScott** [comment]
Removed the unneeded parser settings in tests

**Comment by fefrei** [comment]
> Nesting memo and forwardref (const Component = React.memo(React.forwardRef(function Component() { /*...*/})) is not currently handled by react so continue to raise an error in that case (see facebook/react#16722)

@BPScott: FYI, it looks like this React issue was [solved in November 2019](https://github.com/facebook/react/pull/17274), so it might make sense to allow this now, too 🙂

**Comment by ljharb** [comment]
@fefrei please feel free to file an issue or a PR!
