### PR TITLE
Fix `no-this-in-sfc` rule behavior for arrow functions inside a class field

### LINKED ISSUE #1967: no-this-in-sfc false positives
The following code triggers ESLint errors on the `this.reset()` line.

```
class Foo {
  unsubscribe(ticketID) { 
    return dispatch => {
      this.reset();
      dispatch(forceUpdate());

      return null;
    };
  }
}
```

There is no React or JSX in this file.

### PR DESCRIPTION
**Pull request by sergei-startsev**
Fixed #1967. Adjusted component detection in `getParentStatelessComponent` for arrow functions inside a class field, e.g.:

```js
class Foo {
  bar() { 
    () => {
      this.something();
      return null;
    };
  }
}
```
See details in #1972.

### CODE REVIEW

File: lib/util/Components.js [hunk 1]
```diff
@@ -486,6 +492,23 @@ function componentRule(rule, context) {
...
 
+    /**
+     * Get a parent scope created by a FunctionExpression or FunctionDeclaration
+     * @param {Scope} scope The child scope
+     * @returns {Scope} A parent function scope
+     */
+    getParentFunctionScope(scope) {
+      scope = scope.upper;
+      while (scope) {
+        const type = scope.block.type;
```
Comment (ljharb) [inline lib/util/Components.js]: will scope always have an object `block` property?

File: lib/util/Components.js [hunk 2]
```diff
@@ -486,6 +492,23 @@ function componentRule(rule, context) {
...
+        if (type === 'FunctionExpression' || type === 'FunctionExpression') {
```
Comment (ljharb) [inline lib/util/Components.js]: Is this meant to be checking the same thing twice?

File: lib/util/Components.js (hunk 1 above)
Comment (sergei-startsev) [reply lib/util/Components.js]: I think yes, here's the [proof](https://github.com/eslint/eslint-scope/blob/3e69fdcf102082f3b3c419d0864d7ed90323f4ca/lib/scope.js#L650). There's also no extra checks in [the code above](https://github.com/yannickcr/eslint-plugin-react/pull/1989/files#diff-bafb3355a409c4ba076a9e3d609ad65bR470).

File: lib/util/Components.js (hunk 2 above)
Comment (sergei-startsev) [reply lib/util/Components.js]: good catch, it should be `FunctionExpression` and `FunctionDeclaration`

**Comment by sergei-startsev** [comment]
Fixed typo and added one more more test.

**Comment by ljharb** [comment]
I don't see any tests of function declarations tho (arrows are only ever expressions)
