### PR TITLE
[fix] `prefer-stateless-function`: avoid crash on ts empty constructor

### LINKED ISSUE #2187: [prefer-stateless-function] not work with @typescript-eslint/parser
```bash
TypeError: Cannot read property 'body' of null
    at properties.some.property (/Users/puwei/Dev/code/ant-design-pro/node_modules/_eslint-plugin-react@7.12.4@eslint-plugin-react/lib/rules/prefer-stateless-function.js:191:52)
    at Array.some (<anonymous>)
    at hasOtherProperties (/Users/puwei/Dev/code/ant-design-pro/node_modules/_eslint-plugin-react@7.12.4@eslint-plugin-react/lib/rules/prefer-stateless-function.js:183:25)
    at Program:exit.Object.keys.forEach.component (/Users/puwei/Dev/code/ant-design-pro/node_modules/_eslint-plugin-react@7.12.4@eslint-plugin-react/lib/rules/prefer-stateless-function.js:361:13)
    at Array.forEach (<anonymous>)
    at Object.Program:exit (/Users/puwei/Dev/code/ant-design-pro/node_modules/_eslint-plugin-react@7.12.4@eslint-plugin-react/lib/rules/prefer-stateless-function.js:359:27)
    at updatedRuleInstructions.(anonymous function) (/Users/puwei/Dev/code/ant-design-pro/node_modules/_eslint-plugin-react@7.12.4@eslint-plugin-react/lib/util/Components.js:756:75)
    at listeners.(anonymous function).forEach.listener (/Users/puwei/Dev/code/ant-design-pro/node_modules/_eslint@5.15.0@eslint/lib/util/safe-emitter.js:52:26)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/puwei/Dev/code/ant-design-pro/node_modules/_eslint@5.15.0@eslint/lib/util/safe-emitter.js:49:38)
```

### PR DESCRIPTION
**Pull request by golopot**
fixes #2187

Typescript allows constructor without body, like
```ts
class Foo {
  constructor(a)
}
```

This PR adds a null check to avoid crash.

### CODE REVIEW

File: tests/lib/rules/prefer-stateless-function.js [hunk 1]
```diff
@@ -157,6 +157,18 @@ ruleTester.run('prefer-stateless-function', rule, {
...
+      code: `
+        class Foo extends React.Component {
+          constructor(props)
+
+          render() {
+            return <div>{this.props.foo}</div>;
+          }
+        }
+      `,
+      parser: parsers.TYPESCRIPT_ESLINT
```
Comment (golopot) [inline tests/lib/rules/prefer-stateless-function.js]: This is valid test case, similar to the two cases above in line 138 - 156.

**Comment by golopot** [comment]
The build is failing for unrelated reasons.

**Comment by golopot** [comment]
Blocked by #2583.
