### PR TITLE
[Fix] jsx-indent with tabs

### LINKED ISSUE #1057: jsx-indent with tabs fails to error/fix
Here's [a repo](https://github.com/kentcdodds/jsx-indent-bug) that demonstrates this issue.

**Versions**:

- `eslint`: 3.14.1
- `eslint-plugin-react`: 6.9.0

**Config**:

```javascript
{
  "plugins": [
    "react"
  ],
  "parserOptions": {
    "ecmaVersion": 6,
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "rules": {
    "react/jsx-indent": ["error", "tab"],
    "indent": ["error", "tab"],
  }
}
```

**Input**:

```javascript
const React = require('react')
module.exports = MyComponent

function MyComponent(props) {
  return (
    <div
      className="foo-bar"
      id="thing"
    >
      Hello world!
    </div>
  )
}
```

**lint output**:

```
<path>/jsx-indent-bug/index.js
  5:3  error  Expected indentation of 1 tab but found 2 spaces     indent
  6:5  error  Expected indentation of 1 tab character but found 0  react/jsx-indent
```

**`--fix`ed file**:

```javascript
const React = require('react')
module.exports = MyComponent

function MyComponent(props) {
	return (
		<div
      className="foo-bar"
      id="thing"
    >
      Hello world!
    </div>
	)
}
```

After the `--fix`, there are no more linting errors. However this is clearly not indenting lines 7-11 properly.

I'll start working on a PR. I'm pretty sure I can make a failing test, but I'm not certain how I'd fix the issue. Any tips appreciated!

### PR DESCRIPTION
**Pull request by kentcdodds**
This fixes the `--fix` for `jsx-indent`. Specifically my issue was with tabs (Fixes #1057), but this fixes the same issues with spaces as well.

Highlevel important bits:
1. Adds fix for when the ending of a tag (`>`) is on its own line. This will now lint and fix properly.
2. Adds fix for linting and fixing Literal strings inside JSX
3. Adds configuration option called `indentLogicalExpressions` which will allow for indenting the right side of logical expressions (documented)
4. Adds fix for linting and fixing the indentation of the closing tag.

### CODE REVIEW

File: lib/rules/jsx-indent.js [hunk 1]
```diff
@@ -218,41 +220,47 @@ module.exports = {
       }
     }
 
+    function getOpeningElementIndent(node) {
```
Comment (kentcdodds) [inline lib/rules/jsx-indent.js]: Needed to move this because the `JSXClosingElement` needs to get the opening element's indent as it _should be_ not as it is.

**Comment by kentcdodds** [comment]
Getting pretty close on this one!

File: lib/rules/jsx-indent.js [hunk 2]
```diff
@@ -93,46 +95,32 @@ module.exports = {
...
-    function report(node, needed, gotten, loc) {
+    function report(node, needed, gotten, isEndOfTag) {
       var msgContext = {
         needed: needed,
         type: indentType,
         characters: needed === 1 ? 'character' : 'characters',
         gotten: gotten
       };
 
-      if (loc) {
```
Comment (kentcdodds) [inline lib/rules/jsx-indent.js]: I noticed that no calls to `report` were using `loc` anyway, so I could remove `loc` and replace it with the new `isEndOfTag`

File: lib/rules/jsx-indent.js [hunk 3]
```diff
@@ -93,46 +91,35 @@ module.exports = {
...
+    function report(node, needed, gotten, rangeToReplace, loc) {
       var msgContext = {
         needed: needed,
         type: indentType,
         characters: needed === 1 ? 'character' : 'characters',
         gotten: gotten
       };
+      rangeToReplace = rangeToReplace || [node.start - node.loc.start.column, node.start];
 
-      if (loc) {
```
Comment (kentcdodds) [inline lib/rules/jsx-indent.js]: Based on the ESLint docs, if `loc` isn't provided, it defaults to `node.loc` so I figured we could just do the same and save ourselves an if statement :)

File: lib/rules/jsx-indent.js [hunk 4]
```diff
@@ -218,41 +226,78 @@ module.exports = {
...
+        prevToken = sourceCode.getNodeByRangeIndex(prevToken.start);
+        while (prevToken.parent && prevToken.parent.type !== 'ConditionalExpression') {
+          prevToken = prevToken.parent;
+        }
+      }
+      prevToken = prevToken.type === 'JSXExpressionContainer' ? prevToken.expression : prevToken;
+
+      var parentElementIndent = getNodeIndent(prevToken);
+      if (prevToken.type === 'JSXElement') {
+        parentElementIndent = getOpeningElementIndent(prevToken.openingElement);
```
Comment (kentcdodds) [inline lib/rules/jsx-indent.js]: Note the recurssion here.

File: tests/lib/rules/jsx-indent.js [hunk 5]
```diff
@@ -505,22 +529,22 @@ ruleTester.run('jsx-indent', rule, {
       '  );',
       '}'
     ].join('\n'),
-    // The detection logic only thinks <App> is indented wrong, not the other
-    // two lines following. I *think* because it incorrectly uses <App>'s indention
-    // as the baseline for the next two, instead of the realizing the entire three
-    // lines are wrong together. See #608
-    /* output: [
+    output: [
```
Comment (kentcdodds) [inline tests/lib/rules/jsx-indent.js]: Woot! These changes fix this case and we can now auto-fix this!

File: tests/lib/rules/jsx-indent.js [hunk 6]
```diff
@@ -212,17 +214,6 @@ ruleTester.run('jsx-indent', rule, {
     ].join('\n'),
     parserOptions: parserOptions
   }, {
-    // Literals indentation is not touched
```
Comment (kentcdodds) [inline tests/lib/rules/jsx-indent.js]: I think that Literal indentation should be touched as it doesn't make a difference in the resulting HTML (different for JSXExpressions, but that doesn't apply here).

File: tests/lib/rules/jsx-indent.js [hunk 7]
```diff
@@ -51,14 +51,16 @@ ruleTester.run('jsx-indent', rule, {
...
-    code: [
-      '  <App>',
-      '<Foo />',
-      '  </App>'
-    ].join('\n'),
-    options: [-2],
-    parserOptions: parserOptions
+  // }, {
+  // should we put effort in making this work?
+  // who in their right mind would do this?
```
Comment (kentcdodds) [inline tests/lib/rules/jsx-indent.js]: Question stands... It would require more logic in the fixer and I don't think it's worth the complexity.

**Comment by kentcdodds** [comment]
Pinging those who have touched this rule in one way or another: @yannickcr, @Jorundur, @eelyafi, @jayphelps, @petersendidit, @voxpelli

Thanks friends!

**Comment by kentcdodds** [comment]
Don't merge this yet, just found a bug with the following code:

```javascript
<div>
  {
    foo &&
      <div>
        <div></div>
      </div>
  }
</div>
```

We're getting a bad report on the middle-most `div`. Looking into fixing that.

**Comment by kentcdodds** [comment]
Just noticed that this is actually by design (a few valid tests showing this). I'm going to add a config option to enable this style.

**Comment by kentcdodds** [comment]
Ok, I've updated the PR with documentation for the new configuration option `indentLogicalExpressions`

**Comment by kentcdodds** [comment]
Oh, and just an argument for the `indentLogicalExpressions` pattern is the `language-babel` plugin for Atom (761,282 downloads) has an option to auto-indent JSX and this is how it indents things. Also I personally prefer this indentation style FWIW :)

**Comment by kentcdodds** [comment]
I published my branch as `@kentcdodds/eslint-plugin-react` if anyone wants to try it out.

**Comment by kentcdodds** [comment]
I've verified that this works on my work project :+1:

**Comment by jayphelps** [comment]
Is this multiple fixes to separate indention cases?

**Comment by kentcdodds** [comment]
> Is this multiple fixes to separate indention cases?

```
<ng-sheepishly>Yes, it is...</ng-sheepishly>
```

Originally, it was to fix a single issue with `--fix`, but I noticed that in my project we also indent multi-line LogicalExpressions so I slipped that in. I'd definitely prefer to just merge things together (as they are now), but can create a separate PR if people really feel strongly about this...

**Comment by jayphelps** [comment]
It's just a bit hard for me to follow with the various changes for separate things.

**Comment by kentcdodds** [comment]
Understood @jayphelps, if others feel this way, then I'll split things up.

File: lib/rules/jsx-indent.js [hunk 8]
```diff
@@ -218,41 +238,82 @@ module.exports = {
...
+      }
+
+      if (isRightInLogicalExp(node) && indentLogicalExpressions) {
```
Comment (kentcdodds) [inline lib/rules/jsx-indent.js]: This is the only relevant bit for the `indentLogicalExpressions` option.

**Comment by jayphelps** [comment]
Could you perhaps edit the original post to include a summary of the changed behaviors?

File: lib/rules/jsx-indent.js [hunk 9]
```diff
@@ -218,41 +238,82 @@ module.exports = {
...
+        }
+      }
+    }
+
+    /**
+     * Gets what the JSXOpeningElement's indentation should be
+     * @param {ASTNode} node The JSXOpeningElement
+     * @return {Number} the number of indentation characters it should have
+     */
+    function getOpeningElementIndent(node) {
```
Comment (kentcdodds) [inline lib/rules/jsx-indent.js]: This function came from the `JSXOpeningElement` function below. I extracted it to make use of it else where. The only changes from what was there before is the two if statements before the `var indent = (` assignment.

**Comment by kentcdodds** [comment]
Updated, let me know if more details would be helpful. Thanks @jayphelps!

File: lib/rules/jsx-indent.js [hunk 10]
```diff
@@ -218,41 +238,82 @@ module.exports = {
...
+      return parentElementIndent + indent;
+    }
+
     return {
       JSXOpeningElement: function(node) {
         var prevToken = sourceCode.getTokenBefore(node);
         if (!prevToken) {
           return;
         }
-        // Use the parent in a list or an array
```
Comment (kentcdodds) [inline lib/rules/jsx-indent.js]: This code was simply refactored to `getOpeningElementIndent`

File: lib/rules/jsx-indent.js [hunk 11]
```diff
@@ -165,8 +184,9 @@ module.exports = {
       } while (token.type === 'JSXText' && /^\s*$/.test(token.value));
       var startLine = node.loc.start.line;
       var endLine = token ? token.loc.end.line : -1;
+      var whitespaceOnly = token ? /\n\s*$/.test(token.value) : false;
```
Comment (lencioni) [inline lib/rules/jsx-indent.js]: This probably doesn't matter, but I think this regex won't match the first line? Should it be `/^\s*$/` instead? I'm also not sure what `token.value` represents, so perhaps the `\n` is necessary. (see also the regex on line 184)

If these end up being the same, it might not be a bad idea to move them to a constant at the module level.

File: lib/rules/jsx-indent.js (hunk 9 above)
Comment (lencioni) [inline lib/rules/jsx-indent.js]: Thanks for providing this context. This is helpful for reviewers.

File: lib/rules/jsx-indent.js [hunk 12]
```diff
@@ -218,41 +238,82 @@ module.exports = {
...
+    function getOpeningElementIndent(node) {
+      var prevToken = sourceCode.getTokenBefore(node);
+      if (!prevToken) {
+        return 0;
+      }
+      // Use the parent in a list or an array
+      if (prevToken.type === 'JSXText' || prevToken.type === 'Punctuator' && prevToken.value === ',') {
+        prevToken = sourceCode.getNodeByRangeIndex(prevToken.start);
+        prevToken = prevToken.type === 'Literal' ? prevToken.parent : prevToken;
+      // Use the first non-punctuator token in a conditional expression
```
Comment (lencioni) [inline lib/rules/jsx-indent.js]: nit: I find this style of commenting to be pretty awkward. I think this would be best if it was moved inside the conditional branch. Don't worry about this unless you end up touching this again, especially since you didn't write it.

File: tests/lib/rules/jsx-indent.js (hunk 7 above)
Comment (lencioni) [inline tests/lib/rules/jsx-indent.js]: I don't think this is worth supporting.

File: lib/rules/jsx-indent.js (hunk 11 above)
Comment (kentcdodds) [inline lib/rules/jsx-indent.js]: I just tried out changing it to `^` and it results in an additional extraneous error in one of the test cases. Specifically:

```javascript
function MyComponent(props) {
	return (
    <div
			className="foo-bar"
			id="thing"
    >
      Hello world!
    </div>
	)
}
```

Because `token.value` is actually everything between the `>` and the `</div>` (which includes a `\n`)

File: lib/rules/jsx-indent.js (hunk 12 above)
Comment (kentcdodds) [inline lib/rules/jsx-indent.js]: I was in the area and updated the commenting style. I also find it confusing as it is.

File: tests/lib/rules/jsx-indent.js (hunk 7 above)
Comment (kentcdodds) [inline tests/lib/rules/jsx-indent.js]: Great, I went ahead and removed the commented-out code.
