### PR TITLE
fix[jsx-handler-name]: add option to disable property

### LINKED ISSUE #2400: react/jsx-handler-names: cannot opt-out of handler prefix independent of prop prefix
### Issue

I only want to enforce `eventHandlerPropPrefix`, but I cannot selectively opt out of `eventHandlerPrefix`.

---

#### 1. Rule always plugs in a default value 'handle' into `eventHandlerPrefix` when supplied value is an empty string `''` (falsy)

**Problematic code:**

```js
// will always be set to 'handle' when falsy
const eventHandlerPrefix = configuration.eventHandlerPrefix || 'handle';
```
[source](https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/jsx-handler-names.js#L39
)

---

#### 2. Rule prevents "whitelist" JS regex workarounds noted in #1687 because a capital letter must succeed the allowed prefix.

**Example Config:** I want to whitelist `submit` `select` verbatim and `handle*` prefix:

```js
"react/jsx-handler-names": ['error', {
  "eventHandlerPrefix": '(handle|submit|select)',
  "eventHandlerPropPrefix": 'on',
}],
```

**Problematic code:**

```js
// [A-Z] succeeding eventHandlerPrefix prevents handler whitelist
const EVENT_HANDLER_REGEX = new RegExp(`^((props\\.${eventHandlerPropPrefix})|((.*\\.)?${eventHandlerPrefix}))[A-Z].*$`);
```

[source](https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/jsx-handler-names.js#L42)

### PR DESCRIPTION
**Pull request by tanmoyopenroot**
#### PR checklist

- [x] Addresses an existing issue: fixes #2400 
- [x] enhancement
- [x] Includes tests
- [ ] Documentation update

#### Overview of change:
```javascript
    schema: [{
      oneOf: [
        {
          type: 'object',
          properties: {
            eventHandlerPrefix: {type: 'string'},
            eventHandlerPropPrefix: {type: 'string'}
          },
          additionalProperties: false
        }, {
          type: 'object',
          properties: {
            eventHandlerPrefix: {type: 'string'},
            eventHandlerPropPrefix: {
              type: 'boolean',
              enum: [false]
            }
          },
          additionalProperties: false
        }, {
          type: 'object',
          properties: {
            eventHandlerPrefix: {
              type: 'boolean',
              enum: [false]
            },
            eventHandlerPropPrefix: {type: 'string'}
          },
          additionalProperties: false
        }
      ]
    }]
```

### CODE REVIEW

File: lib/rules/jsx-handler-names.js [hunk 1]
```diff
@@ -24,23 +24,42 @@ module.exports = {
       type: 'object',
       properties: {
         eventHandlerPrefix: {
-          type: 'string'
+          type: ['string', 'boolean']
```
Comment (ljharb) [inline lib/rules/jsx-handler-names.js]: can this be made to prevent use of `true`? perhaps `oneOf: [{ type: 'string' }, false]` or similar?

File: lib/rules/jsx-handler-names.js [hunk 2]
```diff
@@ -24,23 +24,42 @@ module.exports = {
...
         }
       },
       additionalProperties: false
     }]
   },
 
   create(context) {
+    function isPrefixDisabled(prefix) {
+      return (
+        typeof prefix === 'boolean' &&
```
Comment (ljharb) [inline lib/rules/jsx-handler-names.js]: this line is redundant with the one after it
```suggestion
```

File: lib/rules/jsx-handler-names.js [hunk 3]
```diff
@@ -24,23 +24,42 @@ module.exports = {
...
-    const eventHandlerPropPrefix = configuration.eventHandlerPropPrefix || 'on';
+    const eventHandlerPrefix = isPrefixDisabled(configuration.eventHandlerPrefix) ?
+      null :
+      configuration.eventHandlerPrefix || 'handle';
+    const eventHandlerPropPrefix = isPrefixDisabled(configuration.eventHandlerPropPrefix) ?
+      null :
+      configuration.eventHandlerPropPrefix || 'on';
+
+    if (!eventHandlerPrefix && !eventHandlerPropPrefix) {
+      throw new Error('Both \'eventHandlerPrefix\' and \'eventHandlerPropPrefix\' cannot be false');
```
Comment (ljharb) [inline lib/rules/jsx-handler-names.js]:
```suggestion
      throw new TypeError('Both \'eventHandlerPrefix\' and \'eventHandlerPropPrefix\' cannot be false');
```

however, this should be enforced via the rule schema, not via runtime JS.

In other words, the schema should allow:
 - string or false
 - false or string
 - string or string

but not "false or false", and no `true`s.

File: lib/rules/jsx-handler-names.js (hunk 1 above)
Comment (tanmoyopenroot) [reply lib/rules/jsx-handler-names.js]: Done

File: lib/rules/jsx-handler-names.js (hunk 2 above)
Comment (tanmoyopenroot) [reply lib/rules/jsx-handler-names.js]: Done

File: lib/rules/jsx-handler-names.js (hunk 3 above)
Comment (tanmoyopenroot) [reply lib/rules/jsx-handler-names.js]: Done

File: lib/rules/jsx-handler-names.js [hunk 4]
```diff
@@ -24,23 +24,56 @@ module.exports = {
...
-    const PROP_EVENT_HANDLER_REGEX = new RegExp(`^(${eventHandlerPropPrefix}[A-Z].*|ref)$`);
+    const eventHandlerPrefix = isPrefixDisabled(configuration.eventHandlerPrefix) ?
+      null :
+      configuration.eventHandlerPrefix || 'handle';
+    const eventHandlerPropPrefix = isPrefixDisabled(configuration.eventHandlerPropPrefix) ?
+      null :
+      configuration.eventHandlerPropPrefix || 'on';
+
+    if (!eventHandlerPrefix && !eventHandlerPropPrefix) {
+      throw new TypeError('Both \'eventHandlerPrefix\' and \'eventHandlerPropPrefix\' cannot be false');
```
Comment (ljharb) [inline lib/rules/jsx-handler-names.js]: i'd also like this to be enforced by the schema, eg one of these three:
1. string / string
1. string / false
1. false / string

Comment (tanmoyopenroot) [reply lib/rules/jsx-handler-names.js]: In the schema definition,
Only allowed  combination are:
1: string / string 
2: string / false
3: false/ string

```javascript
        eventHandlerPrefix: {
          oneOf: [
            {
              type: 'string'
            },
            {
              type: 'boolean',
              enum: [false]
            }
          ]
        },
        eventHandlerPropPrefix: {
          oneOf: [
            {
              type: 'string'
            },
            {
              type: 'boolean',
              enum: [false]
            }
          ]
        }
```

Comment (ljharb) [reply lib/rules/jsx-handler-names.js]: right, i'm suggesting we change the schema so that's not possible.

instead of two schemas, each with two variants (total 4), three schemas (total 3).

Comment (tanmoyopenroot) [reply lib/rules/jsx-handler-names.js]: So, Is this ok?
```javascript
    schema: [{
      oneOf: [
        {
          type: 'object',
          properties: {
            eventHandlerPrefix: {type: 'string'},
            eventHandlerPropPrefix: {type: 'string'}
          },
          additionalProperties: false
        }, {
          type: 'object',
          properties: {
            eventHandlerPrefix: {type: 'string'},
            eventHandlerPropPrefix: {
              type: 'boolean',
              enum: [false]
            }
          },
          additionalProperties: false
        }, {
          type: 'object',
          properties: {
            eventHandlerPrefix: {
              type: 'boolean',
              enum: [false]
            },
            eventHandlerPropPrefix: {type: 'string'}
          },
          additionalProperties: false
        }
      ]
    }]
```

Comment (ljharb) [reply lib/rules/jsx-handler-names.js]: That looks great!

Comment (tanmoyopenroot) [reply lib/rules/jsx-handler-names.js]: Done

Comment (ljharb) [reply lib/rules/jsx-handler-names.js]: that means that this TypeError can never happen, so it can be removed?

Comment (tanmoyopenroot) [reply lib/rules/jsx-handler-names.js]: Oops, True.

Comment (tanmoyopenroot) [reply lib/rules/jsx-handler-names.js]: Done
