### PR TITLE
Fix nested object type spread

### LINKED ISSUE #1255: [prop-types] nested flow object type spread crashes
Essentially the same presentation as #1178, but slightly different (nested or alias) case as proven by PR #1254.

-----

```js
Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
    at buildTypeAnnotationDeclarationTypes (/Users/kross/projects/ui/node_modules/eslint-plugin-react/lib/rules/prop-types.js:478:25)
    at /Users/kross/projects/ui/node_modules/eslint-plugin-react/lib/rules/prop-types.js:490:54
    at iterateProperties (/Users/kross/projects/ui/node_modules/eslint-plugin-react/lib/rules/prop-types.js:359:11)
    at buildTypeAnnotationDeclarationTypes (/Users/kross/projects/ui/node_modules/eslint-plugin-react/lib/rules/prop-types.js:489:11)
    at /Users/kross/projects/ui/node_modules/eslint-plugin-react/lib/rules/prop-types.js:712:38
    at iterateProperties (/Users/kross/projects/ui/node_modules/eslint-plugin-react/lib/rules/prop-types.js:359:11)
    at markPropTypesAsDeclared (/Users/kross/projects/ui/node_modules/eslint-plugin-react/lib/rules/prop-types.js:707:11)
    at Object.ClassDeclaration (/Users/kross/projects/ui/node_modules/eslint-plugin-react/lib/rules/prop-types.js:876:11)
    at Linter.updatedRuleInstructions.(anonymous function) (/Users/kross/projects/ui/node_modules/eslint-plugin-react/lib/util/Components.js:624:75)
    at emitOne (events.js:101:20)
    at Linter.emit (events.js:191:7)

Process finished with exit code 1
```

I finally debugged my case close enough to add a test that breaks the current `master`. 

```js
{
      code: [
        'import type {BasePerson} from \'./types\'',
        'type Props = {',
        '  person: {',
        '   ...$Exact<BasePerson>',
        '   lastname: string',
        '  }',
        '};',
        'class Hello extends React.Component {',
        '  props: Props;',
        '  render () {',
        '    return <div>Hello {this.props.person.firstname}</div>;',
        '  }',
        '}'
      ].join('\n'),
      parser: 'babel-eslint'
    }
```

### PR DESCRIPTION
**Pull request by rosskevin**
Closes #1255 

Object type spreads are ignored, but only at the top level.  This ignores object type spreads at any level.

### CODE REVIEW

File: lib/rules/prop-types.js [hunk 1]
```diff
@@ -482,14 +482,25 @@ module.exports = {
...
           var shapeTypeDefinition = {
             type: 'shape',
             children: {}
           };
           iterateProperties(annotation.properties, function(childKey, childValue) {
-            shapeTypeDefinition.children[childKey] = buildTypeAnnotationDeclarationTypes(childValue);
+            if (!childKey && !childValue) {
+              containsObjectTypeSpread = true;
+            } else {
+              shapeTypeDefinition.children[ childKey ] = buildTypeAnnotationDeclarationTypes(childValue);
```
Comment (ljharb) [inline lib/rules/prop-types.js]: square brackets should not have spaces inside them, please remove those

File: lib/rules/prop-types.js [hunk 2]
```diff
@@ -482,14 +482,25 @@ module.exports = {
...
+            }
           });
+
+          // nested object type spread means we need to ignore/accept everything in this object
+          if (containsObjectTypeSpread) {
+            return true;
+          }
           return shapeTypeDefinition;
+
```
Comment (ljharb) [inline lib/rules/prop-types.js]: this line isn't needed; please remove

File: lib/rules/prop-types.js (hunk 1 above)
Comment (rosskevin) [inline lib/rules/prop-types.js]: Perhaps this project should use eslint to enforce these trivialities?

**Comment by rosskevin** [comment]
I made sure this linted before I submitted the PR.

@ljharb I'll make you a deal, you put in the eslint rules to enforce your review, then I'll open up an editor, hit the backspace key 3 times, lint, commit, and push.

Does that sound in the best interest of this project and making sure noone has to spend time on such trivialities again?

File: lib/rules/prop-types.js (hunk 1 above)
Comment (ljharb) [inline lib/rules/prop-types.js]: Indeed, it should, but since that's the style used a few lines down in the same file, I'd hope it'd be apparent :-)

**Comment by ljharb** [comment]
@rosskevin your attitude isn't going to help get this fix in; I'd rather close it out of hand and never accept the fix into the project, than entertain it :-/

There are plenty of style rules that projects follow that *can't* be linted for, and just because something isn't linted for doesn't mean you don't have to follow that style. Style isn't "triviality".

**Comment by rosskevin** [comment]
Unfortunately, I hit return in my editor and it added spaces to the brackets. I didn't have time to inspect the entire codebase and configure the formatter for the few lines I needed to change for this PR. 

Indeed I didn't touch the line. 

I **strongly** support an enforced style for projects including this one, hence my suggestion that we avoid this wasted time in the future for us or anyone else.  

This is one such reason we put effort into eslint rules, to reduce wasted effort, enforce common style and increase maintainability. I took the lint results and test results at face value and submitted this PR.

After explanation, I would hope you now see my logic in that my positive effort in this PR turns into a frustration.

You may do as you please, I have tried to make a positive contribution by adding good tests and a necessary fix, passing all lint and tests. If you see this as an unworthy contribution, that is certainly your prerogative.

**Comment by ljharb** [comment]
k, rebased it for you on top of a stricter master.

**Comment by rosskevin** [comment]
fixed, thank you @ljharb
