### PR TITLE
Fix issues with IntersectionTypeAnnotation for prop-types and no-unused-prop-types

### LINKED ISSUE #1413: 7.4.0-rc.0 flow imported type intersection error - Cannot read property 'length' of undefined in prop-types.js
We are heavy flow users and are on flow 0.54.0, so I assume this may be related to @jseminck's changes in #1400. This may be an entirely new case or separate bug.

```
 yarn list eslint-plugin-react eslint                                                                                                                                                                   ⏎
yarn list v0.27.5
├─ eslint-plugin-react@7.4.0-rc.0
└─ eslint@4.5.0
```

```
git clone https://github.com/alienfast/material-ui.git
git checkout remove-class-property-props
yarn install
yarn lint
```

```
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at iterateProperties (/Users/kross/projects/material-ui/node_modules/eslint-plugin-react/lib/rules/prop-types.js:365:21)
    at propTypes.types.forEach.annotation (/Users/kross/projects/material-ui/node_modules/eslint-plugin-react/lib/rules/prop-types.js:798:13)
    at Array.forEach (<anonymous>)
    at markPropTypesAsDeclared (/Users/kross/projects/material-ui/node_modules/eslint-plugin-react/lib/rules/prop-types.js:796:27)
    at markAnnotatedFunctionArgumentsAsDeclared (/Users/kross/projects/material-ui/node_modules/eslint-plugin-react/lib/rules/prop-types.js:911:7)
    at Object.handleStatelessComponent (/Users/kross/projects/material-ui/node_modules/eslint-plugin-react/lib/rules/prop-types.js:920:7)
    at Linter.updatedRuleInstructions.(anonymous function) (/Users/kross/projects/material-ui/node_modules/eslint-plugin-react/lib/util/Components.js:666:75)
    at emitOne (events.js:120:20)
    at Linter.emit (events.js:210:7)
    at NodeEventGenerator.applySelector (/Users/kross/projects/material-ui/node_modules/eslint/lib/util/node-event-generator.js:265:26)
```

It appears to be failing when visiting `IntersectionTypeAnnotation`:

prop-types_js_-_material-ui_-____projects_material-ui_

How can I help narrow this down further?

### PR DESCRIPTION
**Pull request by jseminck**
Closes #1413

3 cases needed to be covered:

* Mutliple intersections:

```js
type PropsA = {}
type PropsB = {}
type PropsC = {}
type PropsD = PropsA & PropsB
type Props = PropsC & PropsD
```

* Importing types. This was already handled for other cases, but not for the intersection.
* `type Props = PropsA & { foo: string }`

### CODE REVIEW

File: lib/rules/no-unused-prop-types.js [hunk 1]
```diff
@@ -725,6 +725,70 @@ module.exports = {
...
+          if (!typeNode) {
+            ignorePropsValidation = true;
+          } else if (typeNode.type === 'IntersectionTypeAnnotation') {
+            ignorePropsValidation = declarePropTypesForIntersectionTypeAnnotation(typeNode, declaredPropTypes);
+          } else {
+            ignorePropsValidation = declarePropTypesForObjectTypeAnnotation(typeNode, declaredPropTypes);
+          }
+        }
+
+        return ignorePropsValidation;
```
Comment (ljharb) [inline lib/rules/no-unused-prop-types.js]: i can't decide if this style, or early-returning each place this var is assigned, is better

File: lib/rules/no-unused-prop-types.js [hunk 2]
```diff
@@ -725,6 +725,70 @@ module.exports = {
...
+     * Marks all props found inside IntersectionTypeAnnotation as declared.
+     * Since InterSectionTypeAnnotations can be nested, this handles recursively. 
+     * 
+     * Modifies the declaredPropTypes object
+     * @param {ASTNode} propTypes 
+     * @param {Object} declaredPropTypes 
+     * @returns {Boolean} True if propTypes should be ignored (e.g. when a type can't be resolved, when it is imported)
+     */
+    function declarePropTypesForIntersectionTypeAnnotation(propTypes, declaredPropTypes) {
+      return propTypes.types.reduce((ignorePropsValidation, annotation) => {
```
Comment (ljharb) [inline lib/rules/no-unused-prop-types.js]: since this is reducing to a boolean, could it use `some` or `every`, and that way it will bail early?

File: lib/rules/no-unused-prop-types.js [hunk 3]
```diff
@@ -725,6 +725,70 @@ module.exports = {
...
+      let ignorePropsValidation = false;
+
+      iterateProperties(propTypes.properties, (key, value) => {
+        if (!value) {
+          ignorePropsValidation = true;
+          return;
+        }
+
+        let types = buildTypeAnnotationDeclarationTypes(value, key);
+        if (types === true) {
```
Comment (ljharb) [inline lib/rules/no-unused-prop-types.js]: instead of reusing `types` here, can we use multiple vars and use `const`?

File: lib/rules/no-unused-prop-types.js (hunk 1 above)
Comment (jseminck) [reply lib/rules/no-unused-prop-types.js]: Honestly I'm in general not really happy about the fact that a function with a name `declarePropTypes***` returns a boolean at all. It's a bit confusing. That's why I liked this style a bit more, because it's very explicit to say what those methods return and what the boolean actually means.

Perhaps a `try/catch` may be even better?

File: lib/rules/no-unused-prop-types.js (hunk 3 above)
Comment (jseminck) [reply lib/rules/no-unused-prop-types.js]: This is from the existing code so didn't touch it yet. But I think we can simply do: 

```js
const types = buildTypeAnnotationDeclarationTypes(value, key) || {};
declaredPropTypes.push({
  ...types,
  fullName: key,
  name: key,
  node: value
});
```

Comment (jseminck) [reply lib/rules/no-unused-prop-types.js]: Meh, another problem is that `buildTypeAnnotationDeclarationTypes` returns either a boolean or an object which isn't great either. I try to refactor it to always return an object, but it needs changes in more places than just here. 

But I do think it's a good refactor to do 😄

File: lib/rules/no-unused-prop-types.js (hunk 1 above)
Comment (ljharb) [reply lib/rules/no-unused-prop-types.js]: We could rename the function instead :-)

**Comment by jseminck** [comment]
I started some refactoring based on the comments, but now this currently valid scenario becomes invalid. But IMHO this should be invalid because `firstname` is indeed not declared.

WDYT?

```js
type Props = {name: Object;};
class Hello extends React.Component {
  props: Props;
  render () {
    return <div>Hello {this.props.name.firstname}</div>;
  }
}
```

**Comment by jseminck** [comment]
Made some additional changes. Did a smoke test on the material-ui code which is currently breaking with rc0. I changed those functions to return early, but haven't changed the name as I couldn't come up with something.

@yannickcr please also have a look as this is required for 7.4.0.

File: lib/rules/prop-types.js [hunk 4]
```diff
@@ -261,7 +262,7 @@ module.exports = {
           // If it's a computed property, we can't make any further analysis, but is valid
           return key === '__COMPUTED_PROP__';
         }
-        if (propType === true) {
+        if (typeof propType === 'object' && Object.keys(propType).length === 0) {
```
Comment (ljharb) [inline lib/rules/prop-types.js]: What is the typeof guarding against here? This allows `null`, for example.

File: lib/rules/no-unused-prop-types.js [hunk 5]
```diff
@@ -725,6 +713,60 @@ module.exports = {
...
+    /**
+     * Marks all props found inside IntersectionTypeAnnotation as declared.
+     * Since InterSectionTypeAnnotations can be nested, this handles recursively. 
+     * 
+     * Modifies the declaredPropTypes object
+     * @param {ASTNode} propTypes 
+     * @param {Object} declaredPropTypes 
+     * @returns {Boolean} True if propTypes should be ignored (e.g. when a type can't be resolved, when it is imported)
+     */
+    function declarePropTypesForIntersectionTypeAnnotation(propTypes, declaredPropTypes) {
```
Comment (ljharb) [inline lib/rules/no-unused-prop-types.js]: Can these two functions live somewhere they can be shared across the rules that currently duplicate them?

Comment (jseminck) [reply lib/rules/no-unused-prop-types.js]: Yes. I'm working on it 😄 The idea will be that the rule will be declared as:

```
create: propTypes.detect((context, components, utils) => {
...
})
```

And this will take care of ALL the shared code between `prop-types` and `no-unused-prop-types`. Perhaps also for the other rules.

File: lib/rules/prop-types.js (hunk 4 above)
Comment (jseminck) [reply lib/rules/prop-types.js]: `null` would be checked in the if statement before:

```
if (!propType) {
    // If it's a computed property, we can't make any further analysis, but is valid
    return key === '__COMPUTED_PROP__';
}
```

Otherwise, if I remove the `typeof` condition, one test starts failing. Turns out `propType` in this case is a `function()` (not sure why) and it satifies the condition `Object.keys(propType).length === 0`. Perhaps should use https://www.npmjs.com/package/lodash.isplainobject ?

```
function Hello(props) {
  return <div>{props.name.constructor.firstname}</div>
}
Hello.propTypes = {
  name: PropTypes.shape({
    firstname: PropTypes.object
  })
};:

AssertionError: Should have 1 error but had 0: []
```

Comment (ljharb) [reply lib/rules/prop-types.js]: Gotcha; makes sense.
