### PR TITLE
[Fix]: Does not validate for LogicalExpression

### LINKED ISSUE #2526: react/prop-types does not validate missing propTypes for functions in version 7.17.0
Seems like this is still an issue in version 7.17.0

Missing prop types do not raise errors in a function component with a return of:

```
return (
    ordering.length > 0 && (
      <Paginator items={ordering} pageSize={10} />
    )
)
```

But do with a function component with a return of:

```
  if (ordering.length > 0) {
    return false;
  }

  return (
    <Paginator items={ordering} pageSize={10} />
  )
```

and:

```
  return ordering.length > 0 ? (
    <Paginator items={ordering} pageSize={10} />
  ) : null;
```
_Originally posted by @johnarnfield in https://github.com/yannickcr/eslint-plugin-react/issues/2134#issuecomment-566035325_

### PR DESCRIPTION
**Pull request by toshi-toma**
Fixes #2526.

### CODE REVIEW

File: lib/util/Components.js [hunk 1]
```diff
@@ -373,22 +373,40 @@ function componentRule(rule, context) {
...
         node[property].type === 'ConditionalExpression' &&
         jsxUtil.isJSX(node[property].consequent);
-      const returnsConditionalJSXAlternate = node[property] &&
+        const returnsConditionalJSXAlternate = node[property] &&
         node[property].type === 'ConditionalExpression' &&
         jsxUtil.isJSX(node[property].alternate);
-      const returnsConditionalJSX = strict ?
-        (returnsConditionalJSXConsequent && returnsConditionalJSXAlternate) :
-        (returnsConditionalJSXConsequent || returnsConditionalJSXAlternate);
+        return strict ?
```
Comment (toshi-toma) [inline lib/util/Components.js]: I think `strict` property not used.
I should probably remove `strict` property from `isReturningJSX`.

File: lib/util/Components.js [hunk 2]
```diff
@@ -373,22 +373,40 @@ function componentRule(rule, context) {
         return false;
       }
 
-      const returnsConditionalJSXConsequent = node[property] &&
+      const isReturnsConditionalJSX = () => {
```
Comment (ljharb) [inline lib/util/Components.js]: i'll hoist these functions out so they don't need to be defined every time.

**Comment by toshi-toma** [comment]
Thanks!!
