### PR TITLE
[fix]`jsx-curly-brace-presence`: report unnecessary curly braces on multline child expressions

### LINKED ISSUE #2201: react/jsx-curly-brace-presence {"children": "never"} doesn't error on multiline expressions
```
"eslint": "^4.10.0",
"eslint-plugin-react": "^7.10.0",
```

Given this configuration:

```
'react/jsx-curly-brace-presence': ['error', { props: 'never', children: 'never' }],
```

Unnecessary brackets will be detected when the start tag, children, and end tag are all on the same line, like:

```jsx
<div className={styles.myRateValuePercentSign}>{'%'}</div>
```

but they won't be detected when they're on different lines, like:

```jsx
<div className={styles.myRateValuePercentSign}>
    {'%'}
</div>
```

Is this the intended behavior?

Screen Shot 2019-03-15 at 10 59 45 AM
Screen Shot 2019-03-15 at 10 59 24 AM

### PR DESCRIPTION
**Pull request by vedadeepta**
- [x] Fixes #2201 
- [x] Includes test 

#### Overview of change:
Checks for more than one non-whitespace literal children of `JsxElement` instead of directly checking for `chidlren.length !== 1`.

### CODE REVIEW

File: lib/rules/jsx-curly-brace-presence.js [hunk 1]
```diff
@@ -205,17 +205,44 @@ module.exports = {
...
+      }
+      if (node === children[children.length - 1] && children[children.length - 2]) {
+        return [children[children.length - 2]];
+      }
+      return [];
+    }
+
+    function hasAdjacentJsxExpressionContainers(node, children) {
+      const childrenExcludingWhitespaceLiteral = children.filter(child => !isWhiteSpaceLiteral(child));
+      const adjSiblings = getAdjacentSiblings(node, childrenExcludingWhitespaceLiteral);
```
Comment (taion) [inline lib/rules/jsx-curly-brace-presence.js]: I don't think this check is quite right. We now get stuff like:

```diff
           <div>
-            Confirm{' '}
+            Confirm
             <button type="button" onClick={this.onClickYes}>
```

But this is not the same markup and it's not desirable here.
