### PR TITLE
[Fix] jsx-no-literals with allowStrings doesn't work in props

### LINKED ISSUE #2720: jsx-no-literals with allowStrings doesn't work in props
the following setup seems not to work:

```js
<button type="button" ></button>
```

with the rule 
```js
    'react/jsx-no-literals': [
      'warn',
      {
        noStrings: true,
        allowedStrings: ['button', 'submit'],
      },
    ],
```

produces the following error: `Invalid prop value: “type="button"”  react/jsx-no-literals`

Context: I'm trying to find a balance between enforcing no literals but also `react/button-has-type`

### PR DESCRIPTION
**Pull request by karolina-benitez**
Checks if props string is included in `allowedStrings` option

Fixes #2720.

### CODE REVIEW

File: tests/lib/rules/jsx-no-literals.js [hunk 1]
```diff
@@ -44,6 +44,20 @@ ruleTester.run('jsx-no-literals', rule, {
 
   valid: [
     {
+      code: `
+        class Comp1 extends Component {
+          render() {
+            return (
+              <div>
+                <button type="button" ></button>
```
Comment (ljharb) [inline tests/lib/rules/jsx-no-literals.js:52]:
```suggestion
                <button type="button"></button>
```

File: lib/rules/jsx-no-literals.js [hunk 2]
```diff
@@ -120,7 +120,12 @@ module.exports = {
       },
 
       JSXAttribute(node) {
-        const isNodeValueString = node.value && node.value && node.value.type === 'Literal' && typeof node.value.value === 'string';
+        let isNodeValueString;
+        if (context && context.options[0] && context.options[0].allowedStrings !== undefined) {
+          isNodeValueString = node.value && node.value && node.value.type === 'Literal' && typeof node.value.value === 'string' && context.options[0].allowedStrings.indexOf(node.value) !== -1;
```
Comment (ljharb) [inline lib/rules/jsx-no-literals.js:125]:
```suggestion
          isNodeValueString = node && node.value && node.value.type === 'Literal' && typeof node.value.value === 'string' && context.options[0].allowedStrings.indexOf(node.value) !== -1;
```

File: lib/rules/jsx-no-literals.js [hunk 3]
```diff
@@ -120,7 +120,12 @@ module.exports = {
       },
 
       JSXAttribute(node) {
-        const isNodeValueString = node.value && node.value && node.value.type === 'Literal' && typeof node.value.value === 'string';
+        let isNodeValueString;
+        if (context && context.options[0] && context.options[0].allowedStrings !== undefined) {
```
Comment (ljharb) [inline lib/rules/jsx-no-literals.js:124]: why is this check needed? `config.allowedStrings` should already be an array containing either the default, or the provided value - what's the need to determine what the user actually passed?

File: tests/lib/rules/jsx-no-literals.js [hunk 4]
```diff
@@ -44,6 +44,20 @@ ruleTester.run('jsx-no-literals', rule, {
...
+              </div>
+            );
+          }
+        }
+      `,
+      options: [{noStrings: true, allowedStrings: ['button', 'submit']}],
+      parser: parsers.BABEL_ESLINT
```
Comment (ljharb) [inline tests/lib/rules/jsx-no-literals.js:59]: let's also add the same test case for each of the other parsers (default, and both typescript-eslints)

File: lib/rules/jsx-no-literals.js (hunk 3 above)
Comment (karolina-benitez) [reply lib/rules/jsx-no-literals.js]: Thanks for catching that. Fixed & pushed changes

File: tests/lib/rules/jsx-no-literals.js (hunk 4 above)
Comment (karolina-benitez) [reply tests/lib/rules/jsx-no-literals.js:59]: Can you please clarify?

Comment (ljharb) [reply tests/lib/rules/jsx-no-literals.js:59]: This test case works for babel-eslint; but the same test case should pass on the default parser, and on the old typescript-eslint, and on the new typescript eslint parser.

Comment (karolina-benitez) [reply tests/lib/rules/jsx-no-literals.js:59]: Thanks, added!
