### PR TITLE
[Fix] `display-name`: Get rid of false position on component detection

### LINKED ISSUE #2751: react/display-name false positive on ant-design ColumnsType
**Tell us about your environment**

* **ESLint Version:** 7.5.0
* **ESLint Plugin React Version:** 7.20.3
* **Node Version:** 10.15.3
* **npm Version:** 6.4.1

**What parser (default, Babel-ESLint, etc.) are you using?**

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/eslint-recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:react/recommended',
    'plugin:jsx-a11y/recommended',
    // Prettier plugin and recommended rules
    'prettier/@typescript-eslint',
    'plugin:prettier/recommended',
  ],
  rules: {
    // Include .prettierrc.js rules
    'prettier/prettier': ['error', {}, { usePrettierrc: true }],
    'react/prop-types': 'error',
    'react/react-in-jsx-scope': 'error',
    '@typescript-eslint/explicit-function-return-type': 'error',
    '@typescript-eslint/ban-ts-ignore': 'off',
    'jsx-a11y/label-has-associated-control': [
      'error',
      {
        labelComponents: [],
        labelAttributes: [],
        controlComponents: [],
        assert: 'either',
        depth: 25,
      },
    ],
    'jsx-a11y/anchor-is-valid': 'off',
    '@typescript-eslint/no-explicit-any': 'off',
    '@typescript-eslint/explicit-module-boundary-types': 'error',
    '@typescript-eslint/no-unused-vars': 'error',
  },
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
...
import { ColumnsType } from "antd/lib/table";
import { Table } from "antd";

const profilesColumns: ColumnsType<any> = [
  {
    title: "ID",
    dataIndex: "id",
    key: "id"
  },
  {
    title: "URL",
    dataIndex: "url",
    key: "url",
    render: (url: string): React.ReactElement => (
      <a href={url} target="_blank" rel="noopener noreferrer">
        <p>lol</p>
      </a>
    )
  }
];

ReactDOM.render(
  <Table columns={profilesColumns} />,
  document.getElementById("root")
);
```

```bash
eslint --fix . --ext .ts,.tsx,.js,.jsx
```

**What did you expect to happen?**

For the Ant Design, `render` in `ColumnsType` is not a `React component` but function, hence the rule should not be applied in this scenario. No error should show up.

**What actually happened? Please include the actual, raw output from ESLint.**

```bash
yarn run v1.17.3
$ eslint --fix . --ext .ts,.tsx,.js,.jsx

/home/user/my-project/components/ComponentTable.tsx
  32:13  error  Component definition is missing display name  react/display-name

✖ 1 problem (1 error, 0 warnings)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### LINKED ISSUE #2758: v7.20.6 has breaking changes for react/display-name
before `v7.20.6` the `react/display-name` rule was okay with this pattern:
```jsx
const renderer = a => listItem => (
	<div>{a} {listItem}</div>
);

// for context, that function might be used like this:
<List list={[1, 2, 3]} renderItem={renderer(a)} />
```

Since `v7.20.6` the `react/display-name` rule reports that "Component definition is missing display name" on line 1. 

There's nothing in the changelog for `v7.20.6` regarding the react/display-name rule so I suspect this is unintentional?

I'm also confused as to how we'd fix this because `renderer` is not a component, nor is the function it returns. So maybe this is a false positive?

### PR DESCRIPTION
**Pull request by iiison**
Fixes #2751. Closes #2758.

### CODE REVIEW

File: tests/lib/rules/display-name.js [hunk 1]
```diff
@@ -894,5 +908,21 @@ ruleTester.run('display-name', rule, {
     errors: [{
       message: 'Component definition is missing display name'
     }]
+  }, {
+    code: `
+      const x = {
+        title: "URL",
+        dataIndex: "url",
+        key: "url",
+        render: url => (
```
Comment (jzabala) [inline tests/lib/rules/display-name.js:917]: I don't think that under any conditions this function should be considered a component. Maybe if the name were uppercase, since that is a pattern I have seen in some libraries, something like:

```jsx
<MyComponent.Button />
```

But not this way. What do you think @ljharb ?

Comment (iiison) [reply tests/lib/rules/display-name.js:917]: I thought of the same thing after your last comment on the issue :D  

I am a little new to this codebase. could you please point me to the file/logic where we're classifying the code as a component?

Comment (ljharb) [reply tests/lib/rules/display-name.js:917]: Yes, I agree. This shouldn't be a component.

**Comment by ljharb** [comment]
Please unmark this as a draft when it's updated.

**Comment by k-yle** [comment]
This also fixes #2758

**Comment by koengsen** [comment]
Hey Guys, any news on this one?
