### PR TITLE
[Fix] `boolean-prop-naming`: handle React.FC, intersection, union types

### LINKED ISSUE #3197: react/boolean-prop-naming interface/type on React.FC validation of boolean with typescript does not work
So this works:
```
type Props = {
  enabled: boolean
}
const Hello = (props: Props) => <div />;
```

But If you want to validate a boolaan prop on an interface or type in a React.FC
```

type Props = {
  enabled: boolean;
}

const Hello: React.FC<Props> = ({ enabled }) => {
```

Then it doesnt work and thinks enabled is allowed.
Is this intended?

### PR DESCRIPTION
**Pull request by mobily**
**Types of changes**

This PR fixes #3197, therefore, the `boolean-prop-naming` rule validates correctly the following code: 

```tsx
import type { FC } from 'react' // or import { FC } from 'react'

type Props = {
  enabled: boolean // ❌ error
} 

export const Component: FC<Props> = props => { 
  return <div /> 
}
```

```tsx
import * as React from 'react' 

type Props = {
  enabled: boolean // ❌ error
} 

export const Component: React.FC<Props> = props => { 
  return <div /> 
}
```

```tsx
import type { FC } from 'react' // or import { FC } from 'react'

type Props = {
  isEnabled: boolean // ✅
} 

export const Component: FC<Props> = props => { 
  return <div /> 
}
```

```tsx
import * as React from 'react' 

type Props = {
  isEnabled: boolean // ✅
} 

export const Component: React.FC<Props> = props => { 
  return <div /> 
}
```

Moreover, previously, the plugin could not handle a case like this:

```tsx
import * as React from 'react'
import { BoxProps } from '@mobily/stacks'

type Props = {
  isEnabled: boolean, // ⬅️ this was completely ignored
} & BoxProps

export const Component = (props: Props) => { 
  return <div /> 
}
```

or

```tsx
import * as React from 'react'

type Props = {
  isEnabled: boolean, 
} & {
  lol: boolean, // ⬅️ same here, both property types were ignored
}

export const Component = (props: Props) => { 
  return <div /> 
}
```

Now, the plugin handles the intersection and union types as well, so the following will be validated correctly:

```tsx
import * as React from 'react'

type Props = {
  isEnabled: boolean, // ✅
} & {
  lol: boolean, // ❌ error
}

export const Component = (props: Props) => { 
  return <div /> 
}
```

```tsx
import * as React from 'react'

type Props = {
  isEnabled: boolean, // ✅
} | {
  lol: boolean, // ❌ error
}

export const Component = (props: Props) => { 
  return <div /> 
}
```

```tsx
import * as React from 'react'

type Props = {
  isEnabled: boolean, // ✅
} & ({
  lol: boolean, // ❌ error
} | {
  hasLOL: boolean, // ✅
})

export const Component = (props: Props) => { 
  return <div /> 
}
```

### CODE REVIEW

File: lib/rules/boolean-prop-naming.js [hunk 1]
```diff
@@ -333,7 +361,14 @@ module.exports = {
...
+              propType.forEach((prop) => {
+                validatePropNaming(
+                  list[component].node,
+                  prop.properties || prop.members
+                );
+              });
+            } else if (propType) {
               validatePropNaming(
                 list[component].node,
                 propType.properties || propType.members
```
Comment (ljharb) [inline lib/rules/boolean-prop-naming.js:374]:
```suggestion
            if (propType) {
              [].concat(propType).forEach((prop) => {
                validatePropNaming(
                  list[component].node,
                  prop.properties || prop.members
                );
              });
```

File: tests/lib/rules/boolean-prop-naming.js [hunk 2]
```diff
@@ -417,6 +417,56 @@ ruleTester.run('boolean-prop-naming', rule, {
...
     },
+    {
+      code: `
+        type Props = {
+          isEnabled: boolean
+        } & OtherProps
+        const HelloNew = (props: Props) => { return <div /> };
+      `,
+      options: [{ rule: '^is[A-Z]([A-Za-z0-9]?)+' }],
+      features: ['ts'],
```
Comment (ljharb) [inline tests/lib/rules/boolean-prop-naming.js:428]: does this pass with flow as well?
```suggestion
      features: ['types'],
```

same question throughout

**Review by ljharb — COMMENTED** [review]
Thanks, this is great!

File: lib/rules/boolean-prop-naming.js (hunk 1 above)
Comment (mobily) [reply lib/rules/boolean-prop-naming.js]: ✅

File: tests/lib/rules/boolean-prop-naming.js (hunk 2 above)
Comment (mobily) [reply tests/lib/rules/boolean-prop-naming.js]: @ljharb yes, seems it does! 🎉

**Comment by mobily** [comment]
@ljharb in the meantime, I have added handling the union type, looking forward to your review!

File: lib/rules/boolean-prop-naming.js [hunk 3]
```diff
@@ -228,6 +228,46 @@ module.exports = {
...
+        return component.node.parent.id.typeAnnotation.typeAnnotation.typeParameters.params.find(
+          (param) => param.type === 'TSTypeReference'
+        );
+      }
+    }
+
+    function findTypeAnnotations(identifier, node) {
+      if (node.type === 'TSTypeLiteral') {
+        const currentNode = objectTypeAnnotations.get(identifier.name) || [];
+        currentNode.push(node);
```
Comment (ljharb) [inline lib/rules/boolean-prop-naming.js:262]:
```suggestion
        const currentNode = [].concat(objectTypeAnnotations.get(identifier.name) || [], node);
```
this way we avoid mutation

**Review by ljharb — APPROVED** [review]
Seems great!

**Comment by ljharb** [comment]
hmm, looks like the latest changes you pushed up (or, possibly, my tiny tweaks, but i doubt it) are failing some tests. can you take a look?

**Comment by mobily** [comment]
✅ and done, thanks, @ljharb for tweaking my code a bit!

**Comment by mobily** [comment]
@ljharb ok, I think the most important cases have been handled, could you please run all test suites once again?

**Comment by mobily** [comment]
thank you @ljharb ❤️
