### PR TITLE
[Fix] `display-name`: avoid false positive when React is shadowed

### LINKED ISSUE #3924: [Bug]: display-name false positive when React is shadowed
### Is there an existing issue for this?

- [x] I have searched the existing issues and my issue is unique
- [x] My issue appears in the command-line and not only in the text editor

### Description Overview

`react/display-name` will report an error `Component definition is missing display name` when the `React` global import is shadowed within a function scope.

The same error does not occur for shadowed `memo` or `forwardRef` though.

#### Example

```jsx
import React, { memo, forwardRef } from 'react'

const MixedShadowed = function () {
  const memo = (cb) => cb()
  const { forwardRef } = { forwardRef: () => null }
  const [React] = [{ memo, forwardRef }]

  const Comp = memo(() => {
    return <div>shadowed</div>
  })
  const ReactMemo = React.memo(() => null)
  const ReactForward = React.forwardRef((props, ref) => {
    return `${props} ${ref}`
  })
  const OtherComp = forwardRef((props, ref) => `${props} ${ref}`)

  return [Comp, ReactMemo, ReactForward, OtherComp]
}
```

Running eslint from the command line you'll see the error:

```
  11:21  error  Component definition is missing display name  react/display-name
  12:24  error  Component definition is missing display name  react/display-name
```

### Expected Behavior

I know most people won't shadow `React`, `memo` or `forwardRef`, but I'd still expect the error to not be reported in this case.

### eslint-plugin-react version

v7.37.5

### eslint version

v9.26.0

### node version

v22.15.0

### PR DESCRIPTION
**Pull request by hyeonbinHur**
Fixes #3924

### CODE REVIEW

File: lib/rules/display-name.js [hunk 1]
```diff
@@ -31,32 +31,36 @@ const messages = {
 module.exports = {
   meta: {
     docs: {
-      description: 'Disallow missing displayName in a React component definition',
+      description:
+        'Disallow missing displayName in a React component definition',
```
Comment (ljharb) [inline lib/rules/display-name.js:35]: please don't run prettier on projects that don't use it :-) and please revert all unrelated style changes.

**Review by ljharb — CHANGES_REQUESTED** [review]
can't review til style diffs are reverted

File: lib/rules/display-name.js (hunk 1 above)
Comment (hyeonbinHur) [reply lib/rules/display-name.js]: Sorry, I forgot to disable some style-related settings, which caused unnecessary formatting changes. I’ll remove the unnecessary style edits and commit again soon. Thanks for the review and the feedback!

Comment (ljharb) [reply lib/rules/display-name.js]: My suggestion is to keep those always disabled, and only use eslint to format files.

Comment (morganney) [reply lib/rules/display-name.js]: Except [eslint recommends to use formatters instead](https://eslint.org/blog/2023/10/deprecating-formatting-rules/#what-you-should-do-instead).

File: lib/rules/display-name.js [hunk 2]
```diff
@@ -161,6 +161,89 @@ module.exports = {
...
+    }
+
+    function isIdentifierShadowed(node, identifierName) {
+      let currentNode = node;
+      while (currentNode && currentNode.parent) {
+        currentNode = currentNode.parent;
+        if (
+          currentNode.type === 'FunctionDeclaration'
+          || currentNode.type === 'FunctionExpression'
+          || currentNode.type === 'ArrowFunctionExpression'
```
Comment (morganney) [inline lib/rules/display-name.js:208]: Why only these scopes? For example what about `BlockStatement`:

```
{
  const memo = (cb) => cb()
  const forwardRef = (cb) => cb()
  const React = { memo, forwardRef }

  const BlockReactShadowedMemo = React.memo(() => {
    return <div>shadowed</div>
  })
}
```

Comment (hyeonbinHur) [reply lib/rules/display-name.js:208]: Thank you for the review. Let me take a quick look and try to find a better algorithm to cover all test cases.
