### PR TITLE
[Fix] `jsx-sort-props`: only use localeCompare when case is ignored

### LINKED ISSUE #2381: react/jsx-sort-props gets confused when props are sorted with --fix but one has camelCase
I found this weird issue where props were sorted automatically via the `--fix` option but the last one had a camel case.
The linter would then complain about the camel cased prop being expected before the other.

Example:
```tsx
<Test aa aB />
```

image

The configuration for this was 
```js
'react/jsx-sort-props': [
            'error',
            {
                callbacksLast: true,
                reservedFirst: true,
                shorthandFirst: true,
            },
        ],
```

Adding the flag `ignoreCase: true` removed the error, but obviously that still means there is a bug somewhere.

### PR DESCRIPTION
**Pull request by tanmoyopenroot**
#### PR checklist

- [x] Addresses an existing issue: fixes #2381 #2530 
- [x] bugfix
- [x] Includes tests
- [ ] Documentation update

#### Overview of change:
remove the use  of `localCompare`

### CODE REVIEW

File: lib/rules/jsx-sort-props.js [hunk 1]
```diff
@@ -72,7 +72,7 @@ function contextCompare(a, b, options) {
     aProp = aProp.toLowerCase();
     bProp = bProp.toLowerCase();
   }
-  return aProp.localeCompare(bProp);
```
Comment (ljharb) [inline lib/rules/jsx-sort-props.js]: 1. this needs to return `0` when `aProp === bProp`.
1. i would still prefer to use localeCompare when case is not ignored.

Comment (tanmoyopenroot) [reply lib/rules/jsx-sort-props.js]: I will try to fix it with `localeCompare `.
