### PR TITLE
Fix `prop-types` desctructuring with properties as string.

### LINKED ISSUE #118: 'prop-types' rule doesn't recognize 'this-format' properties name
I wasn't been able to find out such issue. Sorry if I missed one.

```js
propTypes: {
  ...
  'aria-controls': React.PropTypes.string
},

let {
  ...
  'aria-controls': ariaControls,  // <- error 'undefined' is missing in props validation  react/prop-types
  ...props } = this.props; // eslint-disable-line object-shorthand
```
```
error  'undefined' is missing in props validation  react/prop-types
```

### PR DESCRIPTION
**Pull request by Cellule**
Fixes #118 
I saw that destructuring were not correctly detected when the first key was a string and also those were not handled properly.

### CODE REVIEW

File: tests/lib/rules/prop-types.js [hunk 1]
```diff
@@ -415,6 +415,23 @@ eslintTester.addRuleTest('lib/rules/prop-types', {
         classes: true,
         jsx: true
       }
+    }, {
+      code: [
+        'class Hello extends React.Component {',
+        '  render() {',
+        '    var { ',
+        '      propX,',
+        '      "aria-controls": ariaControls, ',
```
Comment (AlexKVal) [inline tests/lib/rules/prop-types.js]: :+1: :smile:

**Comment by AlexKVal** [comment]
Very nice ! :+1: :tada: :rainbow: 
Thank you :cherries:

File: lib/rules/prop-types.js [hunk 2]
```diff
@@ -164,6 +164,16 @@ module.exports = function(context) {
...
   }
 
+  function getKeyValue(node) {
+    var key = node.key;
+    if (key) {
+      if (key.type === 'Identifier') {
+        return key.name;
+      }
+      return key.value;
+    }
```
Comment (AlexKVal) [inline lib/rules/prop-types.js]: why not 
```js
return (key.type === 'Identifier') ? key.name : key.value;
```

here https://github.com/yannickcr/eslint-plugin-react/pull/123/files#diff-6149d4075a6f3125f18ce8c87bb253cbR39 you've done it like that:
```js
return node.key.type === 'Identifier' ? node.key.name : node.key.value;
```

Of course it is just a matter of taste :cherries:

Comment (Cellule) [inline lib/rules/prop-types.js]: The difference is that in `jsx-sort-prop-types` it only checks the propTypes declaration and not its uses.
I was thinking (though I didn't implement it yet) that when checking the uses, you could have the case `const aria = this.props["aria-controls"];`. Right now, this is ignored by the rule because it's a "computed" property. However, I could easily inspect that property, realize it's a literal string value and add the check (there are other implications which is why I haven't done it yet, mostly with case `this.props["some.thing"]` and `name.split(".")` in the rule).
Therefore, I left it with that structure to make it easy to add more checks.
Note that it's possible, but make no sense to do `propType: {["aria-controls"]: React.PropTypes.string};` So they are deliberately ignored in the other rule.

Comment (yannickcr) [inline lib/rules/prop-types.js]: Yep, there is really a lot of different ways to declare/use propTypes, it become hard to check all of them.

**Comment by yannickcr** [comment]
Awesome! Thanks!

File: lib/rules/prop-types.js (hunk 2 above)
Comment (AlexKVal) [inline lib/rules/prop-types.js]: Thank you for the explanation :cherries: :smiley:
