### PR TITLE
Fix indentation of closing parentheses 

### LINKED ISSUE #618: react/jsx-indent: Closing parenthese indentation
The indentation of the closing parentheses on return statements seems to be not working.

The following patterns are considered warnings:

``` js
return (
  <div />
  );
```

``` js
return (
  <div />);
```

The following patterns are not considered warnings:

``` js
return (
  <div />
);
```

``` js
return (<div />);
```

### PR DESCRIPTION
**Pull request by stefanbuck**
This PR will fix the issue describe in https://github.com/yannickcr/eslint-plugin-react/issues/618 where the indentation of the closing parentheses on return statements was not working.

I know some tests are failing, because the existing fixtures doesn't fit with the new behaviour. Therefore I think this should be enabled with an option. Before I fix that, I would like to get some feedback if the implementation is good so far.

Fixes #618.

### CODE REVIEW

**Comment by ljharb** [comment]
This is a bug fix, I don't think it should be an option - I think if the test fixtures are wrong, they are what should be fixed. I'll let @yannickcr comment on the implementation.

**Comment by stefanbuck** [comment]
I see your point, but I'm a bit worried that too many tests would fail because of this change. Just my two cents. The remaining failing tests are fixed with c65bfd7b74f96044d2b778e1e4c2287891efdc93

**Comment by ljharb** [comment]
That just means that too many tests were wrong before. When the changes are just "how many errors" and not "it wasn't an error and now it is", that's not consequential.

**Comment by stefanbuck** [comment]
@yannickcr what do you think about the implementation?

**Comment by stefanbuck** [comment]
I'm still interested in finishing this PR @yannickcr @ljharb

File: tests/lib/rules/jsx-indent.js [hunk 1]
```diff
@@ -137,18 +157,23 @@ ruleTester.run('jsx-indent', rule, {
     ].join('\n'),
     options: [2],
     parserOptions: parserOptions,
-    errors: [{message: 'Expected indentation of 2 space characters but found 9.'}]
+    errors: [
+      {message: 'Expected indentation of 2 space characters but found 9.'},
+      {message: 'Expected indentation of 2 space characters but found 9.'}
```
Comment (yannickcr) [inline tests/lib/rules/jsx-indent.js]: Why do you have 2 errors here? We should only have one in this case (for the closing tag).

**Comment by yannickcr** [comment]
@stefanbuck sorry for the delay :(

File: tests/lib/rules/jsx-indent.js (hunk 1 above)
Comment (stefanbuck) [inline tests/lib/rules/jsx-indent.js]: You're right, it should be only one error. The `openingIndent` and `closingIndent` values are correct, but I think the `report()` is called with the wrong node. I tried to pass the `openingElement` and the `closeingElement` but still it's not working. Do you have anything in mind how to solve this?

**Comment by ljharb** [comment]
@stefanbuck I've rebased your PR branch, but there's still some test failures, and I'm unable to push to it. Can you check the "allow edits" checkbox on the right hand side of the PR? After that, you can check out my changes and iterate from there.

**Comment by stefanbuck** [comment]
@ljharb try it again, please.

**Comment by ljharb** [comment]
@stefanbuck thanks; updated. please delete your local branch, fetch, and re-check out the latest changes, and let's see if we can get this ready to land :-)

**Comment by ljharb** [comment]
@stefanbuck i've rebased this, but tests are failing. can you take another look?

**Comment by stefanbuck** [comment]
@ljharb I'm unable to rebase because of https://github.com/yannickcr/eslint-plugin-react/issues/2525 which is super weird.

**Comment by ljharb** [comment]
Nothing is incorrect here; commit dates are irrelevant. I already rebased the branch for you - if you delete it and check it out fresh, it should work fine.

File: tests/lib/rules/jsx-indent.js [hunk 2]
```diff
@@ -1038,7 +1058,10 @@ const Component = () => (
       '}'
     ].join('\n'),
     options: [2],
-    errors: [{message: 'Expected indentation of 2 space characters but found 9.'}]
+    errors: [
+      {message: 'Expected indentation of 2 space characters but found 9.'},
+      {message: 'Expected indentation of 2 space characters but found 9.'}
+    ]
```
Comment (stefanbuck) [inline tests/lib/rules/jsx-indent.js]: Tests were failing with

```
AssertionError [ERR_ASSERTION]: Should have 1 error but had 2: 

[
  {
    ruleId: 'jsx-indent',
    severity: 1,
    message: 'Expected indentation of 2 space characters but found 9.',
    line: 2,
    column: 3,
    nodeType: 'ReturnStatement',
    endLine: 4,
    endColumn: 17,
    fix: {range: [Array], text: '  '}
  },
  {
    ruleId: 'jsx-indent',
    severity: 1,
    message: 'Expected indentation of 2 space characters but found 9.',
    line: 4,
    column: 10,
    nodeType: 'JSXClosingElement',
    endLine: 4,
    endColumn: 16,
    fix: {range: [Array], text: '  '}
  }
];

+ expected - actual

-2
+1
```

Looks like https://github.com/yannickcr/eslint-plugin-react/pull/1956 added handling for a few similar cases like I did.

**Comment by stefanbuck** [comment]
@ljharb failing tests are fixed

**Comment by ljharb** [comment]
@stefanbuck I've rebased this again adding `output` to the invalid test cases, to test the autofixer, and the tests are failing.

**Comment by ljharb** [comment]
Rebased, and added the fixer changes needed to make the tests pass.

**Review by ljharb — APPROVED** [review]
