### PR TITLE
Fix crash in no-unused-prop-types

### LINKED ISSUE #1542: no-unused-prop-types: Potential regression introduced in 7.5.0
Hi there.

Noticed that my lint step failed after tagging my library with no code changes:

https://travis-ci.org/LINKIWI/react-elemental/builds/304035438
https://travis-ci.org/LINKIWI/react-elemental/builds/304036629

Interestingly, the failing build pulled in 7.5.0 of `eslint-plugin-react` which was published a couple minutes before the build kicked off.

I haven't had time to do thorough investigation yet, but the 7.5.0 release seems to have introduced a regression in `no-unused-prop-types`:

```
Cannot read property 'properties' of undefined

TypeError: Cannot read property 'properties' of undefined

    at markPropTypesAsUsed (/home/travis/build/LINKIWI/react-elemental/node_modules/eslint-plugin-react/lib/rules/no-unused-prop-types.js:658:40)

    at handleSetStateUpdater (/home/travis/build/LINKIWI/react-elemental/node_modules/eslint-plugin-react/lib/rules/no-unused-prop-types.js:955:7)

    at Object.handleFunctionLikeExpressions (/home/travis/build/LINKIWI/react-elemental/node_modules/eslint-plugin-react/lib/rules/no-unused-prop-types.js:964:7)

    at updatedRuleInstructions.(anonymous function) (/home/travis/build/LINKIWI/react-elemental/node_modules/eslint-plugin-react/lib/util/Components.js:654:75)

    at listeners.(anonymous function).forEach.listener (/home/travis/build/LINKIWI/react-elemental/node_modules/eslint/lib/util/safe-emitter.js:47:58)

    at Array.forEach (native)

    at Object.emit (/home/travis/build/LINKIWI/react-elemental/node_modules/eslint/lib/util/safe-emitter.js:47:38)

    at NodeEventGenerator.applySelector (/home/travis/build/LINKIWI/react-elemental/node_modules/eslint/lib/util/node-event-generator.js:251:26)

    at NodeEventGenerator.applySelectors (/home/travis/build/LINKIWI/react-elemental/node_modules/eslint/lib/util/node-event-generator.js:280:22)

    at NodeEventGenerator.enterNode (/home/travis/build/LINKIWI/react-elemental/node_modules/eslint/lib/util/node-event-generator.js:294:14)

    at CodePathAnalyzer.enterNode (/home/travis/build/LINKIWI/react-elemental/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
```

### PR DESCRIPTION
**Pull request by jomasti**
When checking props in setState updater functions, some assumptions were
being made about the props argument being defined.

Fixes #1542

### CODE REVIEW

File: lib/rules/no-unused-prop-types.js [hunk 1]
```diff
@@ -949,7 +949,7 @@ module.exports = {
     }
 
     function handleSetStateUpdater(node) {
-      if (!node.params || !node.params.length || !inSetStateUpdater()) {
+      if (!node.params || !node.params.length || node.params.length < 2 || !inSetStateUpdater()) {
```
Comment (ljharb) [inline lib/rules/no-unused-prop-types.js]: `!node.params.length` is `node.params.length === 0`, so this is now redundant with the "< 2" comparison. let's remove the former.

**Comment by ljharb** [comment]
@yannickcr this also should go in a v7.5.1, ASAP
