### PR TITLE
[Fix] `jsx-no-useless-fragment`: accept fragments with call expressions

### LINKED ISSUE #2584: react/jsx-no-useless-fragment false positive
There's a false positive on the rule with forwarded children. Use cases are pretty rare but still exist. Without a fragment around the `children`, code breaks at runtime

```
const HollowComponent = ({ children }) => {
  // some logic here
  return <>{children}</>; // doesn't pass the rule
}
```

example: https://codesandbox.io/s/icy-lake-ri3uo

Temporary fix is to disable rule for this line but it would be nicer if this rule let this kind of Fragment use possible.

### PR DESCRIPTION
**Pull request by hasparus**
:wave: 

Solves part of #2584.

### CODE REVIEW

File: tests/lib/rules/jsx-no-useless-fragment.js [hunk 1]
```diff
@@ -63,6 +63,10 @@ ruleTester.run('jsx-no-useless-fragment', rule, {
     {
       code: '<Fooo content={<>eeee ee eeeeeee eeeeeeee</>} />',
       parser: parsers.BABEL_ESLINT
+    },
+    {
+      code: '<>{foos.map(foo => foo)}</>',
```
Comment (ljharb) [inline tests/lib/rules/jsx-no-useless-fragment.js:68]: this seems like a useless fragment to me tho? since `foos.map` produces an array, and an array is a valid render value.

File: tests/lib/rules/jsx-no-useless-fragment.js [hunk 2]
```diff
@@ -72,6 +76,12 @@ ruleTester.run('jsx-no-useless-fragment', rule, {
       errors: [{messageId: 'NeedsMoreChidren', type: 'JSXFragment'}],
       parser: parsers.BABEL_ESLINT
     },
+    {
+      code: '<>{}</>',
```
Comment (ljharb) [inline tests/lib/rules/jsx-no-useless-fragment.js:80]: this seems like it's just a syntax error, and wouldn't parse in the first place?

File: tests/lib/rules/jsx-no-useless-fragment.js (hunk 1 above)
Comment (hasparus) [reply tests/lib/rules/jsx-no-useless-fragment.js:68]: **In case if `foos` is an array**, the fragment wraps an array (a React node) into a React element. It's not useless if it's intentional (e.g. a function where you pass this treats arrays different than single elements -- requires a single child or sth like that).

https://github.com/yannickcr/eslint-plugin-react/issues/2584#issuecomment-627002431


**But actually, we can't assume what `map` does**, and even if `map` suggests an array, we treat all call expressions the same.
It may return `undefined` and then we have a crash at runtime if render it without wrapping in the fragment.

```js
const foos = { map: () => undefined };
```

File: tests/lib/rules/jsx-no-useless-fragment.js (hunk 2 above)
Comment (hasparus) [reply tests/lib/rules/jsx-no-useless-fragment.js:80]: It's totally legal. CodeSandbox here:

https://codesandbox.io/s/jsx-no-useless-fragment-qw6cj

In this case the `{}` is useless, so fixing it into `<></>` could be nice.

Comment (ljharb) [reply tests/lib/rules/jsx-no-useless-fragment.js:80]: wow, ok then :-)

File: tests/lib/rules/jsx-no-useless-fragment.js (hunk 1 above)
Comment (ljharb) [reply tests/lib/rules/jsx-no-useless-fragment.js:68]: What crash at runtime? A component that returns `[undefined]` is a valid component.

You're right that it wouldn't be useless if it's being passed somewhere, but since the introduction of fragments it seems like anything that accepts a fragment should also accept an array?

Comment (hasparus) [reply tests/lib/rules/jsx-no-useless-fragment.js:68]: > What crash at runtime? A component that returns [undefined] is a valid component.

Yes, but it's not valid if it returns `undefined`. There is no array here.

This doesn't have to be `map`, but even when the function is called "map" we have no guarantee that this is `Array.prototype.map`. A function may return undefined.

**Comment by Vishwas-75** [comment]
How to disable this jsx-no-useless-frragments

**Comment by ljharb** [comment]
@Vishwas-75 same way to disable any rule; set it to "off" in your eslint config, or with an inline eslint override comment. eslint's docs are a good resource.
