### PR TITLE
[Fix] False positive in `no-this-in-sfc`

### LINKED ISSUE #3054: react/no-this-in-sfc: eslint-plugin-react 7.25.0 interprets an old legacy jQuery plugin as a sfc
I get lot's of false positive `react/no-this-in-sfc` warnings in Typescript (*.ts) Files.
It seems as if TypeScript files with ts (not just tsx) extension would be regarded as react files and of type `$.fn.<lowercase>... = function (): <type> | null` would be interpreted as an `sfc`:

```ts
$.fn.getValueAsStringWeak = function (): string | null {
	const val = this.length === 1 ? this.val() : null;

	return typeof val === 'string' ? val : null;
};
```

### PR DESCRIPTION
**Pull request by Wesitos**
+ Modified `getStatelessComponent` method
+ Added check for functions assigned to properties (property name must be PascalCase)

Fixes #3054

### CODE REVIEW

File: lib/util/Components.js [hunk 1]
```diff
@@ -617,6 +618,13 @@ function componentRule(rule, context) {
       }
 
       if (node.type === 'FunctionExpression' || node.type === 'ArrowFunctionExpression') {
+        const isMethod = parent.type === 'Property' && parent.method;
+        const isPropertyAssignment = parent.type === 'AssignmentExpression'
+              && parent.left.type === 'MemberExpression';
+        const isModuleExportsAssignment = isPropertyAssignment
+              && parent.left.object.name === 'module'
+              && parent.left.property.name === 'exports';
```
Comment (ljharb) [inline lib/util/Components.js:626]:
```suggestion
          && parent.left.type === 'MemberExpression';
        const isModuleExportsAssignment = isPropertyAssignment
          && parent.left.object.name === 'module'
          && parent.left.property.name === 'exports';
```

File: lib/util/Components.js [hunk 2]
```diff
@@ -630,31 +638,36 @@ function componentRule(rule, context) {
...
         }
 
-        // Case like `React.memo(() => <></>)` or `React.forwardRef(...)`
-        const pragmaComponentWrapper = utils.getPragmaComponentWrapper(node);
-        if (pragmaComponentWrapper) {
-          return pragmaComponentWrapper;
+        if (isPropertyAssignment
+            && !isModuleExportsAssignment
+            && !isFirstLetterCapitalized(parent.left.property.name)) {
+          return undefined;
```
Comment (ljharb) [inline lib/util/Components.js:667]:
```suggestion
        if (
          isPropertyAssignment
          && !isModuleExportsAssignment
          && !isFirstLetterCapitalized(parent.left.property.name)
        ) {
          return undefined;
```

**Review by ljharb — APPROVED** [review]
