### PR TITLE
detect used props in jsx

### LINKED ISSUE #885: no-unused-prop-types sometimes fails to detect props in functions on stateless components
Here is a minimal example that triggers this:

``` jsx
const PagingBlock = function(props) {
  return (
    <span>
      <a onClick={() => props.previousPage()}/>
      <a onClick={() => props.nextPage()}/>
    </span>
 );
};

PagingBlock.propTypes = {
  nextPage: React.PropTypes.func.isRequired,
  previousPage: React.PropTypes.func.isRequired,
};
```

The error message is:

```
  18:17  error  'previousPage' PropType is defined but prop is never used  react/no-unused-prop-types
```

Notes:
- Converting this to a React.createClass with static propTypes fixes the issue
- Removing either `<a/>` tag produces the correct lint error, the false error only occurs when both are present
- The error is notified for the first tag (switching `nextPage` and `previousPage` inside the render function will make the error text say `nextPage` is defined but not used

### PR DESCRIPTION
**Pull request by BarryThePenguin**
fixes #885

### CODE REVIEW

File: lib/util/Components.js [hunk 1]
```diff
@@ -347,12 +347,13 @@ function componentRule(rule, context) {
         var isFunction = /Function/.test(node.type); // Functions
         var isMethod = node.parent && node.parent.type === 'MethodDefinition'; // Classes methods
         var isArgument = node.parent && node.parent.type === 'CallExpression'; // Arguments (callback, etc.)
+        var isJSX = node.parent && node.parent.type === 'JSXExpressionContainer';
         // Stop moving up if we reach a class or an argument (like a callback)
         if (isClass || isArgument) {
           return null;
         }
         // Return the node if it is a function that is not a class method
```
Comment (lencioni) [inline lib/util/Components.js]: This comment should probably be updated.

File: lib/util/Components.js [hunk 2]
```diff
@@ -347,12 +347,13 @@ function componentRule(rule, context) {
         var isFunction = /Function/.test(node.type); // Functions
         var isMethod = node.parent && node.parent.type === 'MethodDefinition'; // Classes methods
         var isArgument = node.parent && node.parent.type === 'CallExpression'; // Arguments (callback, etc.)
+        var isJSX = node.parent && node.parent.type === 'JSXExpressionContainer';
```
Comment (lencioni) [inline lib/util/Components.js]: I might be misunderstanding what this is checking for here, but I'm not sure this variable name makes sense. I think `isJSXExpressionContainerExpression` would be more accurate.

Additionally, it might be nice to include a comment with an example of what type of code this identifies.

Comment (lencioni) [inline lib/util/Components.js]: Also, does this bug exist for folks not using JSX? (i.e. `React.createElement`)

```js
React.createElement("a", { onClick: function onClick() {
    return props.previousPage();
  } });
```

File: lib/util/Components.js (hunk 1 above)
Comment (BarryThePenguin) [inline lib/util/Components.js]: Updated

File: lib/util/Components.js (hunk 2 above)
Comment (BarryThePenguin) [inline lib/util/Components.js]: The problem is that functions inside a `JSXExpressionContainer` are bing mistaken for stateless components.

For example: `<button onClick={() => props.handleClick()}></button>`
where `{() => props.handleClick()}` is the`JSXExpressionContainer`
