### PR TITLE
[Fix] version detection: support processor virtual filename

### LINKED ISSUE #2948: `lib/util/version.js:31:31` is not compatible with processors with virtual filename
A lot of rules are incompatible.

```log
Oops! Something went wrong! :(

ESLint: 7.22.0

TypeError: Error while loading rule 'react/display-name': Provided basedir "/Users/JounQin/Workspaces/GitHub/eslint-mdx/README.md" is not a directory, or a symlink to a directory
Occurred while linting /Users/JounQin/Workspaces/GitHub/eslint-mdx/README.md/3_3.js
    at Function.resolveSync [as sync] (/Users/JounQin/Workspaces/GitHub/eslint-mdx/node_modules/eslint-plugin-react/node_modules/resolve/lib/sync.js:91:24)
    at detectReactVersion (/Users/JounQin/Workspaces/GitHub/eslint-mdx/node_modules/eslint-plugin-react/lib/util/version.js:31:31)
    at getReactVersionFromContext (/Users/JounQin/Workspaces/GitHub/eslint-mdx/node_modules/eslint-plugin-react/lib/util/version.js:55:25)
    at Object.testReactVersion (/Users/JounQin/Workspaces/GitHub/eslint-mdx/node_modules/eslint-plugin-react/lib/util/version.js:124:35)
    at usedPropTypesInstructions (/Users/JounQin/Workspaces/GitHub/eslint-mdx/node_modules/eslint-plugin-react/lib/util/usedPropTypes.js:285:48)
    at Function.componentRule (/Users/JounQin/Workspaces/GitHub/eslint-mdx/node_modules/eslint-plugin-react/lib/util/Components.js:966:37)
    at createRuleListeners (/Users/JounQin/Workspaces/GitHub/eslint-mdx/node_modules/eslint/lib/linter/linter.js:761:21)
    at /Users/JounQin/Workspaces/GitHub/eslint-mdx/node_modules/eslint/lib/linter/linter.js:931:31
    at Array.forEach (<anonymous>)
    at runRules (/Users/JounQin/Workspaces/GitHub/eslint-mdx/node_modules/eslint/lib/linter/linter.js:876:34)
```

Can we add a check like following?

https://github.com/prettier/eslint-plugin-prettier/pull/401/files#diff-e9a90fe7b2d3420b8e5f64e24d5f56ffe6383e47b07461172cc29ed21b768905R79-R94

### PR DESCRIPTION
**Pull request by JounQin**
close #2948

cc @ljharb

### CODE REVIEW

File: lib/util/version.js [hunk 1]
```diff
@@ -21,14 +21,33 @@ function resetDetectedVersion() {
...
 }
 
+function resolvePkgPath(pkg, context) {
+  const filepath = context && context.getFilename();
+  const basedir = filepath ? path.dirname(filepath) : process.cwd();
+  try {
+    return resolve.sync(pkg, {basedir});
+  } catch (err) {
+    // https://github.com/eslint/eslint/issues/11989
+    if (err.code !== 'INVALID_BASEDIR' || !/[/\\]\d+_[^/\\]*\.[\da-z]+$/i.test(filepath)) {
```
Comment (ljharb) [inline lib/util/version.js:31]: i'm really not confident about this regex. why do we even need to do the `resolve` call if there's a virtual filename?

File: tests/util/version.js [hunk 2]
```diff
@@ -79,6 +79,22 @@ describe('Version', () => {
...
+    it('works with virtual filename', () => {
+      sinon.stub(context, 'getFilename').callsFake(() => path.resolve(base, 'detect-version-sibling', 'test.js/0_fake.js'));
+
+      assert.equal(versionUtil.testReactVersion(context, '2.3.4'), true);
+      assert.equal(versionUtil.testReactVersion(context, '2.3.5'), false);
+      assert.equal(versionUtil.testFlowVersion(context, '2.92.0'), true);
+    });
+
+    it('throws on invalid virtual filename', () => {
+      sinon.stub(context, 'getFilename').callsFake(() => path.resolve(base, 'detect-version-sibling', 'test.js/fake.js'));
```
Comment (ljharb) [inline tests/util/version.js:92]: i'm confused. what makes this invalid, and the other one valid?

File: tests/util/version.js [hunk 3]
```diff
@@ -79,6 +79,22 @@ describe('Version', () => {
         ['Warning: Flow version was set to "detect" in eslint-plugin-react settings, but the "flow-bin" package is not installed. Assuming latest Flow version for linting.']
       ];
     });
+
+    it('works with virtual filename', () => {
+      sinon.stub(context, 'getFilename').callsFake(() => path.resolve(base, 'detect-version-sibling', 'test.js/0_fake.js'));
```
Comment (ljharb) [inline tests/util/version.js:84]: there's nothing about this filename that actually ensures it's "virtual" - this could absolutely be a real file path.

**Review by ljharb — CHANGES_REQUESTED** [review]

File: lib/util/version.js (hunk 1 above)
Comment (JounQin) [reply lib/util/version.js:31]: `{index}_` prefix is hard coded at https://github.com/eslint/eslint/blob/master/lib/linter/linter.js#L1303

File: tests/util/version.js (hunk 2 above)
Comment (JounQin) [reply tests/util/version.js:92]: As above

File: tests/util/version.js (hunk 3 above)
Comment (JounQin) [reply tests/util/version.js:84]: No, a filename can never be a directory.

`test.js` a true filename, there will never be a `test.js/foo` file.

File: lib/util/version.js (hunk 1 above)
Comment (ljharb) [reply lib/util/version.js:31]: so it kind of seems like, if `path.dirname()` exists and is a file, and if the file does *not* exist, then it's a virtual filename?

**Comment by ljharb** [comment]
What I've been playing with is:
```diff
diff --git a/lib/util/version.js b/lib/util/version.js
index c34b7c55..7f99dd96 100644
--- a/lib/util/version.js
+++ b/lib/util/version.js
@@ -7,6 +7,7 @@
 
 const resolve = require('resolve');
 const path = require('path');
+const fs = require('fs');
 const error = require('./error');
 
 let warnedForMissingVersion = false;
@@ -27,8 +28,20 @@ function detectReactVersion(context) {
     return cachedDetectedReactVersion;
   }
 
+  let basedir = process.cwd();
+  if (context) {
+    const filename = context.getFilename();
+    const fileDir = path.dirname(filename);
+    try {
+      const isFile = fs.statSync(filename).isFile();
+      const fileDirIsDir = fs.statSync(fileDir).isDirectory();
+      if (fileDirIsDir && isFile) {
+        basedir = fileDir;
+      }
+    } catch (e) { /**/ }
+  }
   try {
-    const reactPath = resolve.sync('react', {basedir: context ? path.dirname(context.getFilename()) : process.cwd()});
+    const reactPath = resolve.sync('react', {basedir});
     const react = require(reactPath); // eslint-disable-line global-require, import/no-dynamic-require
     cachedDetectedReactVersion = react.version;
     return cachedDetectedReactVersion;
```

File: tests/util/version.js (hunk 3 above)
Comment (JounQin) [reply tests/util/version.js:84]: Yes, and the test here `test.js` is a true file.

File: lib/util/version.js (hunk 1 above)
Comment (JounQin) [reply lib/util/version.js:31]: @ljharb 

If `path.dirname()` exists and is a file, then the file can never exist, because dirname can not be file and dir at the same time.

I just want to ensure it is a virtual filename generated by ESLint itself specifically instead of passing accidentally by call this package's API.

If you think a loose test is fine, the regexp test can be removed, change to test dirname directly.

Comment (ljharb) [reply lib/util/version.js:31]: Given that eslint itself is being very loose by providing this virtual filename, i'd rather rely on fs methods to detect when this is happening. Nobody is likely to be using this API but us, so I'm not worried about constraining it.

**Comment by JounQin** [comment]
This a flow version test too, so an extra util function is preferred.

File: lib/util/version.js (hunk 1 above)
Comment (JounQin) [reply lib/util/version.js:31]: OK, I'll simply the implementation.

**Comment by ljharb** [comment]
Indeed; my implementation isn't ideal, i just meant the overall approach of using `fs` methods.

**Comment by JounQin** [comment]
@ljharb Done!

File: lib/util/version.js [hunk 4]
```diff
@@ -21,14 +22,36 @@ function resetDetectedVersion() {
...
+
 // TODO, semver-major: remove context fallback
 function detectReactVersion(context) {
   if (cachedDetectedReactVersion) {
     return cachedDetectedReactVersion;
   }
 
   try {
-    const reactPath = resolve.sync('react', {basedir: context ? path.dirname(context.getFilename()) : process.cwd()});
+    const reactPath = resolve.sync('react', {basedir: resolveBasedir(context)});
```
Comment (ljharb) [inline lib/util/version.js:54]: can `resolveBasedir` be moved up out of this try block?

File: lib/util/version.js [hunk 5]
```diff
@@ -21,14 +22,36 @@ function resetDetectedVersion() {
...
+    } catch (err) {
+      // https://github.com/eslint/eslint/issues/11989
+      if (err.code === 'ENOTDIR') {
+        // the error code alreay indicates that dirname is a file
+        basedir = path.dirname(dirname);
+      }
+    }
+  }
+  // fallback to cwd only if basedir not resolved
+  return basedir || process.cwd();
```
Comment (ljharb) [inline lib/util/version.js:44]: how is this any different than `let basedir = process.cwd()` at the beginning?

File: lib/util/version.js (hunk 4 above)
Comment (JounQin) [reply lib/util/version.js:54]: I don't see any difference. The caught error will be rethrown.

File: lib/util/version.js (hunk 5 above)
Comment (JounQin) [reply lib/util/version.js:44]: `process.cwd()` will only be called when necessary.

Comment (ljharb) [reply lib/util/version.js:44]: It costs nothing to call it, though.

File: lib/util/version.js (hunk 4 above)
Comment (ljharb) [reply lib/util/version.js:54]: Code that never throws shouldn't be inside a `try`, or it will run more slowly for no reason.

Comment (JounQin) [reply lib/util/version.js:54]: Is there any reference that `try` is `slow`? I'd prefer cleaner codes.

File: lib/util/version.js (hunk 5 above)
Comment (JounQin) [reply lib/util/version.js:44]: Well, less function calls seems better to me.

File: lib/util/version.js (hunk 4 above)
Comment (ljharb) [reply lib/util/version.js:54]: Either way, it's far cleaner to only put "code that can throw" inside of `try` than to avoid calling `process.cwd()`.

File: lib/util/version.js (hunk 5 above)
Comment (ljharb) [reply lib/util/version.js:44]: then every node program would be prohibitively slow.

**Comment by JounQin** [comment]
@ljharb Although I disagree with your opinion, but these changes are just simple, so Done!

**Review by ljharb — APPROVED** [review]
Thanks, this looks great

**Comment by JounQin** [comment]
@ljharb Is there a schedule to release a patch version? I think it is a serious issue because the original version breaks.

**Comment by ljharb** [comment]
I've just published v7.23.1.

**Comment by JounQin** [comment]
Thanks, although the CHANGELOG seems incorrect.

image

**Comment by ljharb** [comment]
That's quite correct. There's nothing unreleased at the moment.

**Comment by JounQin** [comment]
I mean `[7.23.1]`, see #2950

**Comment by ljharb** [comment]
ah yes, thanks, a copypaste error.
