### PR TITLE
Fix no-comment-textnodes incorrectly catching urls (fixes #664)

### LINKED ISSUE #664: `no-comment-textnodes` false positive on URL
I have JSX like the following:
```js
<strong>
  &nbsp;https://www.example.com/attachment/download/1
</strong>
```

Since the line doesn't start with `//` or `/*`, there shouldn't be any way this is identified as an accidental leaked comment.

### PR DESCRIPTION
**Pull request by petersendidit**
Fixes #664.

### CODE REVIEW

**Comment by ljharb** [comment]
@petersendidit if you rebase on latest master, your tests should pass.

**Comment by ljharb** [comment]
I'd forgotten to update the appveyor config - it's done now.

File: lib/rules/no-comment-textnodes.js [hunk 1]
```diff
@@ -19,7 +19,7 @@ module.exports = function(context) {
 
   return {
     Literal: function(node) {
-      if (/\s*\/(\/|\*)/.test(node.value)) {
+      if (/^\s*\/(\/|\*)/m.test(node.value)) {
```
Comment (ljharb) [inline lib/rules/no-comment-textnodes.js]: since this is just testing the start of a quasi-comment, does it need the "m"?

Comment (petersendidit) [inline lib/rules/no-comment-textnodes.js]: Without the `m` modifier things like this would fail:
```javascript
<div>
  asdjfl
  /* invalid */
  foo
</div>
```

Comment (ljharb) [inline lib/rules/no-comment-textnodes.js]: ah right, i'm assuming the text node will be split up by lines, and that's not likely to be the case.

Could we add your example as a test, to prevent a regression?

Comment (petersendidit) [inline lib/rules/no-comment-textnodes.js]: It's already a test https://github.com/yannickcr/eslint-plugin-react/blob/master/tests/lib/rules/no-comment-textnodes.js#L170

Comment (ljharb) [inline lib/rules/no-comment-textnodes.js]: ah, understood, thanks for clarifying :-)

**Comment by ljharb** [comment]
@yannickcr ping :-)

**Comment by yannickcr** [comment]
Merged, thanks!
