### PR TITLE
fix[jsx-curly-brace-presence] Fix error related to tag line breaks

### LINKED ISSUE #1727: react/jsx-curly-brace-presence "children" "always" complains about whitespace
```
"eslint": "^4.18.2",
"eslint-plugin-react": "^7.6.1",
```

I have the prop: `"react/jsx-curly-brace-presence":["error", { "props": "always", "children": "always" }],` in my `.eslintrc` file because I'm trying to convert:

```jsx
<div className="NameCapture_wrapper">
    <p className="NameCapture__question">
        What's your first name?
    </p>
    <NameCaptureNameInput/>
</div>
```
to:
```jsx
<div className={`NameCapture_wrapper`}>
    <p className={`NameCapture__question`}>
        {`What's your first name?`}
    </p>
    <NameCaptureNameInput/>
</div>
```
but eslint is complaining about the whitespace:

```
  10:44  error  Need to wrap this literal in a JSX expression          react/jsx-curly-brace-presence
  13:49  error  Need to wrap this literal in a JSX expression          react/jsx-curly-brace-presence
  14:56  error  Need to wrap this literal in a JSX expression          react/jsx-curly-brace-presence
  17:53  error  Need to wrap this literal in a JSX expression          react/jsx-curly-brace-presence
  18:45  error  Need to wrap this literal in a JSX expression          react/jsx-curly-brace-presence
  19:23  error  Need to wrap this literal in a JSX expression          react/jsx-curly-brace-presence
```

Below is what fixes it but I shouldn't have to put all of my JSX on one line right?
```jsx
<div className={`NameCapture_wrapper`}><p className={`NameCapture__question`}>{`What's your first name?`}</p><NameCaptureNameInput/></div>
```

### PR DESCRIPTION
**Pull request by rafbgarcia**
Fixes #1727 

#### Before:

```
  4107 passing (7s)
  1 failing

  1) jsx-curly-brace-presence
       valid

        <MyComponent prop="asdasd">
          <div>
            <p>
              <span>
                {"foo"}
              </span>
            </p>
          </div>
        </MyComponent>
      :

      AssertionError [ERR_ASSERTION]: Should have no errors but had 8: [ { ruleId: 'jsx-curly-brace-presence',
    severity: 1,
    message: 'Need to wrap this literal in a JSX expression.',
    line: 2,
    column: 36,
    nodeType: 'Literal',
    endLine: 3,
    endColumn: 11 },
  { ruleId: 'jsx-curly-brace-presence',
    severity: 1,
    message: 'Need to wrap this literal in a JSX expression.',
    line: 3,
    column: 16,
    nodeType: 'Literal',
    endLine: 4,
    endColumn: 13 },
  { ruleId: 'jsx-curly-brace-presence',
    severity: 1,
    message: 'Need to wrap this literal in a JSX expression.',
    line: 4,
    column: 16,
    nodeType: 'Literal',
    endLine: 5,
    endColumn: 15 },
  { ruleId: 'jsx-curly-brace-presence',
    severity: 1,
    message: 'Need to wrap this literal in a JSX expression.',
    line: 5,
    column: 21,
    nodeType: 'Literal',
    endLine: 6,
    endColumn: 17 },
  { ruleId: 'jsx-curly-brace-presence',
    severity: 1,
    message: 'Need to wrap this literal in a JSX expression.',
    line: 6,
    column: 24,
    nodeType: 'Literal',
    endLine: 7,
    endColumn: 15 },
  { ruleId: 'jsx-curly-brace-presence',
    severity: 1,
    message: 'Need to wrap this literal in a JSX expression.',
    line: 7,
    column: 22,
    nodeType: 'Literal',
    endLine: 8,
    endColumn: 13 },
  { ruleId: 'jsx-curly-brace-presence',
    severity: 1,
    message: 'Need to wrap this literal in a JSX expression.',
    line: 8,
    column: 17,
    nodeType: 'Literal',
    endLine: 9,
    endColumn: 11 },
  { ruleId: 'jsx-curly-brace-presence',
    severity: 1,
    message: 'Need to wrap this literal in a JSX expression.',
    line: 9,
    column: 17,
    nodeType: 'Literal',
    endLine: 10,
    endColumn: 9 } ]
      + expected - actual

      -8
      +0
```

### CODE REVIEW

**Comment by rafbgarcia** [comment]
@ljharb can you please take a look as this is currently a blocker to use this lint?

File: lib/rules/jsx-curly-brace-presence.js [hunk 1]
```diff
@@ -322,7 +325,7 @@ module.exports = {
       },
 
       'Literal, JSXText': (node) => {
-        if (shouldCheckForMissingCurly(node.parent, userConfig)) {
+        if (shouldCheckForMissingCurly(node.parent, node, userConfig)) {
```
Comment (ljharb) [inline lib/rules/jsx-curly-brace-presence.js]:
```suggestion
        if (shouldCheckForMissingCurly(node, userConfig)) {
```

File: lib/rules/jsx-curly-brace-presence.js [hunk 2]
```diff
@@ -298,7 +298,10 @@ module.exports = {
       return areRuleConditionsSatisfied(parent, config, OPTION_NEVER);
     }
 
-    function shouldCheckForMissingCurly(parent, config) {
+    function shouldCheckForMissingCurly(parent, node, config) {
+      if (node.raw.trim() === '') {
+        return false;
+      }
```
Comment (ljharb) [inline lib/rules/jsx-curly-brace-presence.js]:
```suggestion
      }
      const parent = node.parent;
```

**Comment by rafbgarcia** [comment]
@ljharb do you plan to release a patch version for this bug or should I use master for now?

**Comment by ljharb** [comment]
I plan to release a version soon, yes (it'll be a minor, i suspect).

**Comment by rafbgarcia** [comment]
I found other edge cases and am working on fixes.

**Comment by ljharb** [comment]
That's great, I look forward to the PRs.
