### PR TITLE
Fix false positives in no-literals

### LINKED ISSUE #1301: no-literals: only check strings
should the no-literals rule check if the `node.value` is a string? with the new `{ "noStrings": true }` option (https://github.com/yannickcr/eslint-plugin-react/pull/1202) I'm getting errors for explicitly set boolean and number props `booleanprop={true}` `numberprop={100}`

### PR DESCRIPTION
**Pull request by davidyorr**
This rule should only check strings.

Fixes #1301

### CODE REVIEW

File: lib/rules/jsx-no-literals.js [hunk 1]
```diff
@@ -44,6 +44,7 @@ module.exports = {
 
     function getValidation(node) {
       const standard = !/^[\s]+$/.test(node.value) &&
+          typeof node.value === 'string' &&
```
Comment (ljharb) [inline lib/rules/jsx-no-literals.js]: hm, i'm kind of confused - what's the typeof `node.value` if it's an object, or a function? Can you add some test cases for that?

Comment (davidyorr) [inline lib/rules/jsx-no-literals.js]: it looks like the `Literal` visitor doesn't hit the node when it's an object or function.

**Comment by davidyorr** [comment]
as is, template strings are not causing linting errors, which they should be. i can look into that as well

File: lib/rules/jsx-no-literals.js (hunk 1 above)
Comment (ljharb) [inline lib/rules/jsx-no-literals.js]: So when would the typeof not be "string"?

Comment (davidyorr) [inline lib/rules/jsx-no-literals.js]:
```javascript
<Foo
  a={true}
  b={1}
  c={null} />
```
all of those props get hit, so typeof could be `boolean`, `number`, and when null it's an `object`

Comment (ljharb) [inline lib/rules/jsx-no-literals.js]: Interesting. Arrays and objects and regexes and functions are all literals too, so it's weird they wouldn't show up. Thanks for explaining.

Comment (davidyorr) [inline lib/rules/jsx-no-literals.js]: yeah i'm not sure why

**Comment by davidyorr** [comment]
updated to check for template literals too

File: tests/lib/rules/jsx-no-literals.js [hunk 2]
```diff
@@ -127,6 +127,48 @@ ruleTester.run('jsx-no-literals', rule, {
...
+      code: '<Foo bar={100} />',
+      parser: 'babel-eslint',
+      options: [{noStrings: true}]
+    }, {
+      code: '<Foo bar={null} />',
+      parser: 'babel-eslint',
+      options: [{noStrings: true}]
+    }, {
+      code: '<Foo bar={{}} />',
+      parser: 'babel-eslint',
```
Comment (ljharb) [inline tests/lib/rules/jsx-no-literals.js]: babel-eslint isn't needed for any of these new tests; let's please prefer the default parser whenever possible.

Comment (davidyorr) [inline tests/lib/rules/jsx-no-literals.js]: babel-eslint isn't needed for any of the tests in this entire PR, or just the last commit? how can I tell which tests need babel-eslint?

Comment (ljharb) [inline tests/lib/rules/jsx-no-literals.js]: tl;dr: if they don't generate a syntax error with the default parser, they don't need babel-eslint :-)

Generally tho, the default parser supports everything that's actually in JS. Things that aren't in JS (or aren't yet), like class properties, require babel-eslint.

Comment (davidyorr) [inline tests/lib/rules/jsx-no-literals.js]: ah okay i see thanks! i'll remove those tests

Comment (ljharb) [inline tests/lib/rules/jsx-no-literals.js]: keeping the tests is great! i just want them using the default parser :-)

Comment (davidyorr) [inline tests/lib/rules/jsx-no-literals.js]: alright deleted the babel parser tests and kept the default parser ones
