### PR TITLE
fix(jsx-sort-props): enforce prop sort when reservedFirst is enabled

### LINKED ISSUE #1320: react/jsx-sort-props not working
I seem to be having trouble getting this rule to work.  The documentation references the following interface:
```
"react/jsx-sort-props": [<enabled>, {
  "callbacksLast": <boolean>,
  "shorthandFirst": <boolean>,
  "shorthandLast": <boolean>,
  "ignoreCase": <boolean>,
  "noSortAlphabetically": <boolean>,
  "reservedFirst": <boolean>|<array<string>>,
}]
```

My current configuration is `"react/jsx-sort-props": [2]`.  I have omitted the options which seem to work fine for other rules in the library.  Don't get any errors for the following component:
```
<Component c="c" b="b" a="a" />
```

### PR DESCRIPTION
**Pull request by tagoro9**
If reservedFirst is enabled and noSortAlphabetically is off, then alphabetical order is only enforced in the reserved props but not in the other props. This PR fixes this.

If existing behavior is the desired, please ignore this PR.

Fixes #1320

### CODE REVIEW

File: tests/lib/rules/jsx-sort-props.js [hunk 1]
```diff
@@ -202,9 +202,19 @@ ruleTester.run('jsx-sort-props', rule, {
...
+    {
+      code: '<App b a />',
+      options: reservedFirstAsBooleanArgs,
+      errors: [expectedError]
+    },
+    {
       code: '<App dangerouslySetInnerHTML={{__html: "EPR"}} key={2} b />',
       options: reservedFirstAsBooleanArgs,
-      errors: [expectedReservedFirstError]
+      errors: [expectedReservedFirstError, expectedError]
```
Comment (ljharb) [inline tests/lib/rules/jsx-sort-props.js]: why would this suddenly start giving two errors?

Comment (tagoro9) [inline tests/lib/rules/jsx-sort-props.js]: I think that after the changes this is triggering the `expectedError` as the `||
 (!previousIsReserved && !currentIsReserved)` check and it is true when evaluating `dangerouslySetInnerHTML` and `b`.

**Comment by tagoro9** [comment]
I updated the tests with the expected output, but I the fix is not taking into account the reserved words:

Expected: `<App key={2} b dangerouslySetInnerHTML={{__html: "EPR"}} />`
Actual : `<App b dangerouslySetInnerHTML={{__html: "EPR"}} key={2} />`

I'm gonna try to see if I can add a fix for this.

File: tests/lib/rules/jsx-sort-props.js (hunk 1 above)
Comment (ljharb) [inline tests/lib/rules/jsx-sort-props.js]: We should try to avoid generating the extra error.

File: tests/lib/rules/jsx-sort-props.js [hunk 2]
```diff
@@ -202,9 +202,19 @@ ruleTester.run('jsx-sort-props', rule, {
...
     },
     {
+      code: '<App key={2} b a />',
+      options: reservedFirstAsBooleanArgs,
+      errors: [expectedError]
+    },
+    {
+      code: '<App b a />',
+      options: reservedFirstAsBooleanArgs,
+      errors: [expectedError]
```
Comment (ljharb) [inline tests/lib/rules/jsx-sort-props.js]: please add `output: '<App a b />'`

File: tests/lib/rules/jsx-sort-props.js [hunk 3]
```diff
@@ -202,9 +202,19 @@ ruleTester.run('jsx-sort-props', rule, {
       errors: [expectedError]
     },
     {
+      code: '<App key={2} b a />',
+      options: reservedFirstAsBooleanArgs,
+      errors: [expectedError]
```
Comment (ljharb) [inline tests/lib/rules/jsx-sort-props.js]: Please add `output: <App key={2} a b />` (assuming that's the expected output)

**Comment by tagoro9** [comment]
Sorry I took so long to take a look at the change requests.

* This [test](https://github.com/yannickcr/eslint-plugin-react/pull/1340/files#diff-85e28e7b3c88362eeaef8cf73f4ad42aR284) is no longer expecting 2 errors.
* Added expected output for the new test cases.
* With the expected output the tests were failing, so I updated the `generateFixerFunction` to take into account the `reservedFirst` config and sort props accordingly. Is this something wanted?

**Comment by ljharb** [comment]
Definitely wanted, thanks :-)

File: tests/lib/rules/jsx-sort-props.js [hunk 4]
```diff
@@ -269,8 +269,21 @@ ruleTester.run('jsx-sort-props', rule, {
...
+    {
+      code: '<App b a />',
+      options: reservedFirstAsBooleanArgs,
+      output: '<App a b />',
+      errors: [expectedError]
+    },
+    {
       code: '<App dangerouslySetInnerHTML={{__html: "EPR"}} key={2} b />',
       options: reservedFirstAsBooleanArgs,
+      output: '<App key={2} b dangerouslySetInnerHTML={{__html: "EPR"}} />',
```
Comment (ljharb) [inline tests/lib/rules/jsx-sort-props.js]: hmm - with reservedFirst tho, the expected output should be `<App dangerouslySetInnerHTML={{__html: "EPR"}} key={2} b />`, no?

Comment (tagoro9) [inline tests/lib/rules/jsx-sort-props.js]: I think `dangerouslySetInnerHTML` is not a reserved prop name for this component. I think it is only considered reserved for DOM components and not react components. This [code](https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/jsx-sort-props.js#L208) is deleting `dangerouslySetInnerHTML` for the cases where the component is not a DOM component.

Comment (ljharb) [inline tests/lib/rules/jsx-sort-props.js]: ahhhh true! good call :-) could you add an "e" prop as well, so it's clear that it's being sorted as a regular property?

Comment (tagoro9) [inline tests/lib/rules/jsx-sort-props.js]: Added.

**Comment by ljharb** [comment]
Planning to merge this soon.

**Comment by tobyf93** [comment]
Is there a reason why this change hasn't been merged in?

**Comment by tobyf93** [comment]
Any idea on when the merge will happen @ljharb?
