### PR TITLE
[jsx curly brace presence]: fix jsx tags in braces

### LINKED ISSUE #2416: jsx-curly-brace-presence does not complain about JSX tags in braces
This should raise an error, right?

```jsx
<div>{ <span></span> }</div>
```

### PR DESCRIPTION
**Pull request by tanmoyopenroot**
#### PR checklist

- [x] Addresses an existing issue: fixes #2416 
- [x] bug
- [x] Includes tests
- [ ] Documentation update

#### Overview of change:
Check for single `JSXElement` in child.

### CODE REVIEW

File: tests/lib/rules/jsx-curly-brace-presence.js [hunk 1]
```diff
@@ -96,7 +96,8 @@ ruleTester.run('jsx-curly-brace-presence', rule, {
       options: [{props: 'never'}]
     },
     {
-      code: '<App>{<myApp></myApp>}</App>'
+      code: '<App>{<myApp></myApp>}</App>',
```
Comment (ljharb) [inline tests/lib/rules/jsx-curly-brace-presence.js]: this arguably is a breaking change :-/ hopefully we can consider this a patch though.
