### PR TITLE
jsx-wrap-multilines now catches single missing newlines

### LINKED ISSUE #1965: jsx-wrap-multilines wrong behavior of parens-new-line
Setting `{ return: 'parens-new-line' }` option should validate that there is a new line after `(` and before `)`.
So following code is the valid code:
```
return (
    <div>
        <div>example</div>
    <div>
)
```

But following code also considered as valid whereas as it isn't:
```
return (<div>
        <div>example</div>
    <div>
)
```

and this one also:
```
return (
    <div>
        <div>example</div>
    <div>)
```

So, the issue occurs when there is one parenthesis on a separate line and another one on the same line with the JSX code.

### PR DESCRIPTION
**Pull request by MrHen**
Fixes #1965. The only interesting question is how the fixer should treat the newlines. I chose to make it add a new line if there was exactly zero after or before the parens. This means:

```
  var Hello = createReactClass({
    render: function() {
      return (<div>
        <p>Hello {this.props.name}</p>
      </div>
      );
    }
  });
```

Fixes to:

```
  var Hello = createReactClass({
    render: function() {
      return (
<div>
        <p>Hello {this.props.name}</p>
      </div>
      );
    }
  });
```

----

And:

```
  var Hello = createReactClass({
    render: function() {
      return (<div>
        <p>Hello {this.props.name}</p>
      </div>

      );
    }
  });
```

Fixes to:

```
  var Hello = createReactClass({
    render: function() {
      return (
<div>
        <p>Hello {this.props.name}</p>
      </div>

      );
    }
  });
```

----

The alternative would be to make exactly _one_ newline regardless of how many there were before -- but I assumed such a behavior should be its own rule instead of attached to this rule.

### CODE REVIEW

File: tests/lib/rules/jsx-wrap-multilines.js [hunk 1]
```diff
@@ -501,7 +525,7 @@ const ATTR_PAREN_NEW_LINE_AUTOFIX_FRAGMENT = `
 `;
 
 function addNewLineSymbols(code) {
-  return code.replace(/\(</g, '(\n<').replace(/>\)/g, '>\n)');
+  return code.replace(/\((\s*)</g, '($1\n<').replace(/>(\s*)\)/g, '>\n$1)');
```
Comment (ljharb) [inline tests/lib/rules/jsx-wrap-multilines.js]: i know this code is already in master, but this makes the test cases very inscrutable :-/

i feel like i'd much rather see an explicit `output` example for each input.

File: lib/rules/jsx-wrap-multilines.js [hunk 2]
```diff
@@ -98,9 +98,19 @@ module.exports = {
       const previousToken = sourceCode.getTokenBefore(node);
       const nextToken = sourceCode.getTokenAfter(node);
 
-      return isParenthesised(node) &&
-        previousToken.loc.end.line === node.loc.start.line &&
```
Comment (ljharb) [inline lib/rules/jsx-wrap-multilines.js]: it seems like the effective change here is changing `&&` to `||`?

File: tests/lib/rules/jsx-wrap-multilines.js (hunk 1 above)
Comment (MrHen) [reply tests/lib/rules/jsx-wrap-multilines.js]: Yeah, me too. I can add explicit output for the tests touched by this PR.

File: lib/rules/jsx-wrap-multilines.js (hunk 2 above)
Comment (MrHen) [reply lib/rules/jsx-wrap-multilines.js]: Yes. I find mixing `&&` and `||` harder to read but if you prefer it that way I can switch it back.

Comment (ljharb) [reply lib/rules/jsx-wrap-multilines.js]: Nah this is good, just making sure i understand.

Comment (MrHen) [reply lib/rules/jsx-wrap-multilines.js]: Apparently I didn't quite understand how the nodes worked with whitespace. I had to break this up into separate functions since the newlines were getting attached to the previous token.

File: tests/lib/rules/jsx-wrap-multilines.js [hunk 3]
```diff
@@ -86,6 +86,56 @@ const RETURN_PAREN_NEW_LINE = `
   });
 `;
 
+const RETURN_PAREN_NEW_LINE_OPENING = `
+  var Hello = createReactClass({
+    render: function() {
+      return (
+
```
Comment (ljharb) [inline tests/lib/rules/jsx-wrap-multilines.js]: These extra newlines here seem odd - why is this allowed to be here?

Comment (MrHen) [reply tests/lib/rules/jsx-wrap-multilines.js]: See my earlier comment: 
https://github.com/yannickcr/eslint-plugin-react/pull/1984#issue-215844164

My first attempts at fixing this caused extraneous newlines to disappear which seemed like an undesired side-effect of this particular rule. The extra newline isn't being added by the fix -- its in the original test condition. The test is making sure the extra newline is _not_ being stripped.

Comment (ljharb) [reply tests/lib/rules/jsx-wrap-multilines.js]: That makes sense (although I’d want it stripped, this probably isn’t the rule for it)

**Comment by MrHen** [comment]
Thanks for the review @ljharb. What's the next step to getting this merged? Anything I need to do?
