### PR TITLE
[Fix]`no-unknown-property`: fix case like `<Foo.bar>`

### LINKED ISSUE #2204: react/no-unknown-property incorrect `for` on none `label` tag detection
I have a `Table.Index` component with `for` prop.

the rule enforces me to use `htmlFor` instead and incorrectly auto replaces it when I run `eslint --fix`

### PR DESCRIPTION
**Pull request by golopot**
Fixes #2204

### CODE REVIEW

File: lib/rules/no-unknown-property.js [hunk 1]
```diff
@@ -167,6 +167,20 @@ function getTagName(node) {
...
 }
 
+/**
+ * Test wether the tag name for the JSXAttribute is
+ * something like <Foo.bar />
+ * @param {JSXAttribute} node - JSXAttribute being tested.
+ * @returns {Boolean} result
+ */
+function tagNameHasDot(node) {
+  return Boolean(
```
Comment (ljharb) [inline lib/rules/no-unknown-property.js]:
```suggestion
  return !!(
```

Comment (golopot) [reply lib/rules/no-unknown-property.js]: Updated
