### PR TITLE
[Fix]: false positives for `no-unused-...` when using TS type assertions

### LINKED ISSUE #2517: no-unused-prop-types returns false positive when destructuring props cast to a different type
# Sample Code

```tsx
const propTypes = {
  foo: PropTypes.number.isRequired,
};

type Props = PropTypes.InferProps<typeof propTypes>;

const Foo: React.FC<Props> = (props) => {
  const {
    foo,
  } = props as any; // works if `as any` assertion is removed

  return (
    <>{foo}</>
  );
};
```

# Issue

The linter throws an error: `'foo' PropType is defined but prop is never used` even tho the prop is used.

# Expected

The linter should not care about props being asserted to be of a different type. If an assertion is made it's most likely for a good reason and the actual prop is still referenced inside the component (no matter its type).

### PR DESCRIPTION
**Pull request by kdmadej**
Fixes #2517:
* adds an ast util for unwrapping TS `as` assertion.
* fixes false positives for `no-unused-prop-types`
* fixes false positives for `no-unused-state`

I tried to reuse as much of the existing solution as possible by handling cases where the `as` expression might occur.

I'm wondering tho if it would be better to just process the code with anything that would remove TS-specific syntax (type annotations, `as` assertions, etc.) and then parse the result so the entire logic could be reused. Just thinking out loud 😅

### CODE REVIEW

File: tests/lib/rules/no-unused-prop-types.js [hunk 1]
```diff
@@ -3136,6 +3135,73 @@ ruleTester.run('no-unused-prop-types', rule, {
...
+            thisPropsAliasProp,
+            thisDestructPropsAliasDestructProp,
+            thisDestructPropsAliasProp,
+            thisDestructPropsDestructProp,
+            thisPropsDestructProp,
+            thisPropsProp,
+          };
+
+          componentDidUpdate(prevProps) {
+            (prevProps as any).prevProp as any;
```
Comment (ljharb) [inline tests/lib/rules/no-unused-prop-types.js]: can we use `unknown` instead of `any` in all these tests?

Comment (kdmadej) [reply tests/lib/rules/no-unused-prop-types.js]: Sure thing. Not sure it changes anything in this case but I'm more then fine with spreading the `unknown` 😄

File: tests/lib/rules/no-unused-prop-types.js [hunk 2]
```diff
@@ -3136,6 +3135,73 @@ ruleTester.run('no-unused-prop-types', rule, {
 
         Foo.defaultProps = Object.assign({});
       `
+    }, {
+      code: `
+        const Foo = (props) => {
+          const { foo } = props as unknown;
+          (props as unknown).bar as unknown;
```
Comment (ljharb) [inline tests/lib/rules/no-unused-prop-types.js]: could we also add this same component as a failing test, with only one of these two propTypes present?

File: tests/lib/rules/no-unused-prop-types.js [hunk 3]
```diff
@@ -3136,6 +3135,73 @@ ruleTester.run('no-unused-prop-types', rule, {
...
+        Foo.propTypes = {
+          foo,
+          bar,
+        };
+      `,
+      parser: parsers.TYPESCRIPT_ESLINT
+    }, {
+      code: `
+        class Foo extends React.Component {
+          static propTypes = {
```
Comment (ljharb) [inline tests/lib/rules/no-unused-prop-types.js]: same here; it'd be great to get this test also as a failing one, with some propTypes present and some not.
