### PR TITLE
Fix display-name when JSON style is used for defining components

### LINKED ISSUE #590: display-name rule quotes handling
If JSON style is used for defining components, rule is not handle "displayName" option.
The following patterns are considered warnings:
`var Hello = React.createClass({
  "displayName": "Hello",
  "render": function() {
    return <div>Hello {this.props.name}</div>;
  }
});`
but its valid code i think.

### PR DESCRIPTION
**Pull request by gitim**
Fixes #590. 

Imho, it is not very common style to define components, but I think it should be fixed.

### CODE REVIEW

File: lib/rules/display-name.js [hunk 1]
```diff
@@ -24,23 +24,25 @@ module.exports = Components.detect(function(context, components, utils) {
...
+      case 'Identifier':
+        return node.name === 'displayName';
+      case 'Literal':
+        return node.value === 'displayName';
+      default:
+        return false;
     }
-
-    return Boolean(
-      node &&
```
Comment (gitim) [inline lib/rules/display-name.js]: Is this check is necessary? All tests passes without it.

File: lib/rules/display-name.js [hunk 2]
```diff
@@ -24,23 +24,25 @@ module.exports = Components.detect(function(context, components, utils) {
...
-    if (node.type === 'ClassProperty') {
-      var tokens = sourceCode.getFirstTokens(node, 2);
-      if (
-        tokens[0].value === 'displayName' ||
-        (tokens[1] && tokens[1].value === 'displayName')
-      ) {
-        return true;
-      }
-      return false;
+    switch (node.type) {
```
Comment (gitim) [inline lib/rules/display-name.js]: I rewrote this with switch statement. I had an option to add another if statement or ternary operator to the last return, but switch seems more explicitly defining possible cases
