### PR TITLE
[fix]`prop-types`: fix case with destructuring and default param

### LINKED ISSUE #2241: prop-types not enforced with destructured props and default empty object param
```
// complains about 'baz' missing from prop-types validation
const Component = ({ foo, bar, baz }) => (
  // ...JSX
);

// doesn't complain about 'baz' missing from prop-types validation
const Component = ({ foo, bar, baz } = {}) => (
  // ...JSX
);

Component.propTypes = {
  foo: PropTypes.string,
  bar: PropTypes.string,
};
```

Since it's generally best-practice to provide defaults when destructuring, it would be nice if passing an empty object as a default param didn't break prop-types validation.

### PR DESCRIPTION
**Pull request by golopot**
fixes #2241

### CODE REVIEW

File: lib/util/usedPropTypes.js [hunk 1]
```diff
@@ -421,7 +422,15 @@ module.exports = function usedPropTypesInstructions(context, components, utils)
    *   FunctionDeclaration, or FunctionExpression
    */
   function markDestructuredFunctionArgumentsAsUsed(node) {
-    const destructuring = node.params && node.params[0] && node.params[0].type === 'ObjectPattern';
+    const param = inSetStateUpdater()
```
Comment (ljharb) [inline lib/util/usedPropTypes.js]:
```suggestion
    const param = node.params && inSetStateUpdater() ? node.params[1] : node.params[0];
```

File: lib/util/usedPropTypes.js [hunk 2]
```diff
@@ -421,7 +422,15 @@ module.exports = function usedPropTypesInstructions(context, components, utils)
    *   FunctionDeclaration, or FunctionExpression
    */
   function markDestructuredFunctionArgumentsAsUsed(node) {
-    const destructuring = node.params && node.params[0] && node.params[0].type === 'ObjectPattern';
+    const param = node.params && inSetStateUpdater() ? node.params[1] : node.params[0];
+      ? node.params && node.params[1]
+      : node.params && node.params[0];
```
Comment (ljharb) [inline lib/util/usedPropTypes.js]:
```suggestion
```

File: lib/util/usedPropTypes.js [hunk 3]
```diff
@@ -421,7 +422,15 @@ module.exports = function usedPropTypesInstructions(context, components, utils)
    *   FunctionDeclaration, or FunctionExpression
    */
   function markDestructuredFunctionArgumentsAsUsed(node) {
-    const destructuring = node.params && node.params[0] && node.params[0].type === 'ObjectPattern';
+    const param = node.params && inSetStateUpdater() ? node.params[1] : node.params[0];
+      ? node.params && node.params[1]
```
Comment (ljharb) [inline lib/util/usedPropTypes.js]:
```suggestion
```

**Comment by golopot** [comment]
Thank you.
