### PR TITLE
Fix jsx-no-bind reporting errors on render functions

### LINKED ISSUE #663: `jsx-no-bind` errors on non-react components.
I have Backbone views with a "render" method that are being warned when they have `.bind` used within them. Did something change recently that loosened the criteria for identifying a React component?

If the `render` method doesn't return JSX, and the component doesn't `extend React.Component`, and most importantly if the file itself doesn't even import/require `React`, why are these rules applying to it?

### PR DESCRIPTION
**Pull request by petersendidit**
Fix jsx-no-bind reporting errors on render functions that don't return JSX (Fixes #663)

### CODE REVIEW

File: lib/rules/jsx-no-bind.js [hunk 1]
```diff
@@ -5,13 +5,25 @@
...
 
+var Components = require('../util/Components');
 var propName = require('jsx-ast-utils/propName');
 
 // -----------------------------------------------------------------------------
 // Rule Definition
 // -----------------------------------------------------------------------------
 
-module.exports = function(context) {
+function renderReturnsJSX(node, utils) {
```
Comment (ljharb) [inline lib/rules/jsx-no-bind.js]: this seems like it might be common behavior that all the rules could use - and that some may already have implemented?

Comment (petersendidit) [inline lib/rules/jsx-no-bind.js]: I agree. Sounds like we should move it to the `utils` provided by the `Components` utility?  What should it be named? There is already a `isReturningJSX` that does the bulk of this work but this deals with finding the `ReturnStatement`

Comment (ljharb) [inline lib/rules/jsx-no-bind.js]: Is there a reason that `isReturningJSX` isn't already checking for a return statement?

Comment (petersendidit) [inline lib/rules/jsx-no-bind.js]: It currently expects a `ReturnStatement` or a `ArrowFunctionExpression` to be passed in.

Comment (petersendidit) [inline lib/rules/jsx-no-bind.js]: We could make the default for the case statement to find a return the `ReturnStatement`

Comment (ljharb) [inline lib/rules/jsx-no-bind.js]: I think it makes sense for "is returning JSX" to accept any kind of function or `class`, and it should be able to accurately return a boolean.

Comment (petersendidit) [inline lib/rules/jsx-no-bind.js]: Updated it to make `isReturningJSX` to handle more nodes.

File: tests/lib/rules/jsx-no-bind.js [hunk 2]
```diff
@@ -121,6 +144,18 @@ ruleTester.run('jsx-no-bind', rule, {
       errors: [{message: 'JSX props should not use .bind()'}],
       parser: 'babel-eslint'
     },
+    {
+      code: [
+        'const foo = {',
+        '  render: function() {',
```
Comment (ljharb) [inline tests/lib/rules/jsx-no-bind.js]: can we also cover the `render() {` case?

File: tests/lib/rules/jsx-no-bind.js [hunk 3]
```diff
@@ -72,6 +72,29 @@ ruleTester.run('jsx-no-bind', rule, {
...
+        '    this.onTap.bind(this);',
+        '  }',
+        '});'
+      ].join('\n'),
+      parser: 'babel-eslint'
+    },
+    {
+      code: [
+        'const foo = {',
+        '  render: function() {',
```
Comment (ljharb) [inline tests/lib/rules/jsx-no-bind.js]: similarly here with `render() {`

Comment (petersendidit) [inline tests/lib/rules/jsx-no-bind.js]: Added

File: tests/lib/rules/jsx-no-bind.js (hunk 2 above)
Comment (petersendidit) [inline tests/lib/rules/jsx-no-bind.js]: Added

**Comment by yannickcr** [comment]
Merged, thanks!
